Repository PI-Akatsuki/PIOMS.BE, pull requests merged in 2024-06, with the labels that each got.

#262 Refactoring every Log Code BE
  src/main/java/com/akatsuki/pioms/admin/service/AdminInfoServiceImpl.java
  src/main/java/com/akatsuki/pioms/categoryFirst/service/CategoryFirstServiceImpl.java
  src/main/java/com/akatsuki/pioms/categorySecond/service/CategorySecondServiceImpl.java
  src/main/java/com/akatsuki/pioms/categoryThird/service/CategoryThirdServiceImpl.java
  src/main/java/com/akatsuki/pioms/company/service/CompanyServiceImpl.java
  src/main/java/com/akatsuki/pioms/franchise/service/FranchiseServiceImpl.java
  src/main/java/com/akatsuki/pioms/frowner/service/FranchiseOwnerServiceImpl.java
  src/main/java/com/akatsuki/pioms/login/service/LoginServiceImpl.java
  src/main/java/com/akatsuki/pioms/product/service/ProductServiceImpl.java
Labels: 🔨 Refactor

#263 User 3 types of token issuance and circular reference resolutio
  build.gradle
  src/main/java/com/akatsuki/pioms/admin/aggregate/Admin.java
  src/main/java/com/akatsuki/pioms/admin/dto/AdminDTO.java
  src/main/java/com/akatsuki/pioms/admin/repository/AdminRepository.java
  src/main/java/com/akatsuki/pioms/admin/service/AdminInfoService.java
  src/main/java/com/akatsuki/pioms/admin/service/AdminInfoServiceImpl.java
  src/main/java/com/akatsuki/pioms/config/ConvertUser.java
  src/main/java/com/akatsuki/pioms/config/SecurityConfig.java
  src/main/java/com/akatsuki/pioms/driver/aggregate/DeliveryDriver.java
  src/main/java/com/akatsuki/pioms/driver/repository/DeliveryDriverRepository.java
  src/main/java/com/akatsuki/pioms/driver/service/DeliveryDriverServiceImpl.java
  src/main/java/com/akatsuki/pioms/franchise/aggregate/Franchise.java
  src/main/java/com/akatsuki/pioms/franchise/dto/FranchiseDTO.java
  src/main/java/com/akatsuki/pioms/frowner/aggregate/FranchiseOwner.java
  src/main/java/com/akatsuki/pioms/frowner/dto/FranchiseOwnerDTO.java
  src/main/java/com/akatsuki/pioms/frowner/repository/FranchiseOwnerRepository.java
  src/main/java/com/akatsuki/pioms/jwt/CustomLogoutFilter.java
  src/main/java/com/akatsuki/pioms/jwt/JWTFilter.java
  src/main/java/com/akatsuki/pioms/jwt/JWTUtil.java
  src/main/java/com/akatsuki/pioms/jwt/LoginFilter.java
  src/main/java/com/akatsuki/pioms/login/aggregate/AdminLoginRequest.java
  src/main/java/com/akatsuki/pioms/login/controller/LoginController.java
  src/main/java/com/akatsuki/pioms/login/controller/ReissueController.java
  src/main/java/com/akatsuki/pioms/login/service/LoginService.java
  src/main/java/com/akatsuki/pioms/login/service/LoginServiceImpl.java
  src/main/java/com/akatsuki/pioms/login/service/RedisTokenService.java
  src/main/java/com/akatsuki/pioms/order/controller/AdminOrderController.java
  src/main/java/com/akatsuki/pioms/order/controller/FranchiseOrderController.java
  src/main/java/com/akatsuki/pioms/order/service/AdminOrderFacade.java
  src/main/java/com/akatsuki/pioms/order/service/FranchiseOrderFacade.java
  src/main/java/com/akatsuki/pioms/user/aggregate/User.java
  src/main/java/com/akatsuki/pioms/user/dto/CustomUserDetails.java
  src/main/java/com/akatsuki/pioms/user/repository/UserRepository.java
  src/main/java/com/akatsuki/pioms/user/service/CustomUserDetailsService.java
Labels: 🐞 BugFix, ✨ Feature, 🔨 Refactor

#264 Spring Security user permission settings
  src/main/java/com/akatsuki/pioms/config/SecurityConfig.java
Labels: 🐞 BugFix, 🔨 Refactor

#265 Fix, refactor, feat: Fixing and refecting errors that occurred during interaction with the browser, add get user code, name with token
  src/main/java/com/akatsuki/pioms/config/ConvertUser.java
  src/main/java/com/akatsuki/pioms/exchange/aggregate/RequestExchange.java
  src/main/java/com/akatsuki/pioms/exchange/controller/AdminExchangeController.java
  src/main/java/com/akatsuki/pioms/exchange/controller/FranchiseExchangeController.java
  src/main/java/com/akatsuki/pioms/exchange/service/ExchangeService.java
  src/main/java/com/akatsuki/pioms/exchange/service/ExchangeServiceImpl.java
  src/main/java/com/akatsuki/pioms/frowner/service/FranchiseOwnerServiceImpl.java
  src/main/java/com/akatsuki/pioms/frwarehouse/controller/franchiseWarehouseController.java
  src/main/java/com/akatsuki/pioms/frwarehouse/service/FranchiseWarehouseService.java
  src/main/java/com/akatsuki/pioms/frwarehouse/service/FranchiseWarehouseServiceImpl.java
  src/main/java/com/akatsuki/pioms/image/service/ImageService.java
  src/main/java/com/akatsuki/pioms/order/controller/AdminOrderController.java
  src/main/java/com/akatsuki/pioms/order/controller/FranchiseOrderController.java
  src/main/java/com/akatsuki/pioms/order/service/AdminOrderFacade.java
  src/main/java/com/akatsuki/pioms/order/service/FranchiseOrderFacade.java
  src/main/java/com/akatsuki/pioms/order/service/OrderServiceImpl.java
  src/main/java/com/akatsuki/pioms/product/controller/AdminProductController.java
  src/main/java/com/akatsuki/pioms/product/service/ProductService.java
  src/main/java/com/akatsuki/pioms/product/service/ProductServiceImpl.java
Labels: 🐞 BugFix, 💻 CrossBrowsing, ✨ Feature, 🔨 Refactor

#267 hot-fix: fix erros of check Authentication
  src/main/java/com/akatsuki/pioms/config/ConvertUser.java
  src/main/java/com/akatsuki/pioms/config/SecurityConfig.java
  src/main/java/com/akatsuki/pioms/exchange/service/ExchangeServiceImpl.java
  src/main/java/com/akatsuki/pioms/frwarehouse/service/FranchiseWarehouseServiceImpl.java
  src/main/java/com/akatsuki/pioms/order/service/AdminOrderFacade.java
  src/main/java/com/akatsuki/pioms/order/service/FranchiseOrderFacade.java
Labels: 🐞 BugFix

#268 fix,refactor: found jwt wrong word, add GetUserInfo
  src/main/java/com/akatsuki/pioms/config/GetUserInfo.java
  src/main/java/com/akatsuki/pioms/frwarehouse/service/FranchiseWarehouseServiceImpl.java
  src/main/java/com/akatsuki/pioms/jwt/JWTFilter.java
  src/main/java/com/akatsuki/pioms/order/service/AdminOrderFacade.java
  src/main/java/com/akatsuki/pioms/order/service/FranchiseOrderFacade.java
Labels: 🐞 BugFix, ✨ Feature

#271 Excel up-to-date download for product by Root,Fr
  src/main/java/com/akatsuki/pioms/excel/ProductExcelAdminController.java
  src/main/java/com/akatsuki/pioms/product/service/ProductServiceImpl.java
Labels: 🐞 BugFix, ✨ Feature, 🔨 Refactor, 📬 API

#272 Added head office inventory notification function
  src/main/java/com/akatsuki/pioms/config/KakaoProperties.java
  src/main/java/com/akatsuki/pioms/config/SecurityConfig.java
  src/main/java/com/akatsuki/pioms/exchange/service/ExchangeServiceImpl.java
  src/main/java/com/akatsuki/pioms/jwt/CustomLogoutFilter.java
  src/main/java/com/akatsuki/pioms/product/controller/AdminProductController.java
  src/main/java/com/akatsuki/pioms/product/dto/KakaoAlertRequest.java
  src/main/java/com/akatsuki/pioms/product/service/ProductService.java
  src/main/java/com/akatsuki/pioms/product/service/ProductServiceImpl.java
Labels: ✨ Feature

#274 View DriverDashboard Status Count Function Implementation
  src/main/java/com/akatsuki/pioms/invoice/controller/DriverInvoiceController.java
  src/main/java/com/akatsuki/pioms/invoice/service/InvoiceService.java
  src/main/java/com/akatsuki/pioms/invoice/service/InvoiceServiceImpl.java
Labels: ✨ Feature, 🔨 Refactor

#275 Refactor: refactoring Ask, FranchiseWarehouse BE
  src/main/java/com/akatsuki/pioms/ask/controller/AskFranchiseController.java
  src/main/java/com/akatsuki/pioms/frwarehouse/controller/franchiseWarehouseController.java
  src/main/java/com/akatsuki/pioms/frwarehouse/repository/FranchiseWarehouseRepository.java
  src/main/java/com/akatsuki/pioms/frwarehouse/service/FranchiseWarehouseService.java
  src/main/java/com/akatsuki/pioms/frwarehouse/service/FranchiseWarehouseServiceImpl.java
Labels: ✨ Feature, 🔨 Refactor

#276 feat, fix: Implementation of Admin, Root dashboard. add logic of check enable to delivery
  src/main/java/com/akatsuki/pioms/dashboard/aggregate/ResponseAdminDashBoard.java
  src/main/java/com/akatsuki/pioms/dashboard/controller/DashboardController.java
  src/main/java/com/akatsuki/pioms/dashboard/service/DashboardService.java
  src/main/java/com/akatsuki/pioms/dashboard/service/DashboardServiceImpl.java
  src/main/java/com/akatsuki/pioms/exchange/service/ExchangeServiceImpl.java
  src/main/java/com/akatsuki/pioms/franchise/repository/FranchiseRepository.java
  src/main/java/com/akatsuki/pioms/franchise/service/FranchiseService.java
  src/main/java/com/akatsuki/pioms/franchise/service/FranchiseServiceImpl.java
  src/main/java/com/akatsuki/pioms/frowner/dto/FranchiseOwnerDTO.java
  src/main/java/com/akatsuki/pioms/order/aggregate/OrderStat.java
  src/main/java/com/akatsuki/pioms/order/repository/OrderRepository.java
  src/main/java/com/akatsuki/pioms/order/service/AdminOrderFacade.java
  src/main/java/com/akatsuki/pioms/order/service/FranchiseOrderFacade.java
  src/main/java/com/akatsuki/pioms/order/service/OrderService.java
  src/main/java/com/akatsuki/pioms/order/service/OrderServiceImpl.java
  src/main/java/com/akatsuki/pioms/product/service/ProductServiceImpl.java
Labels: 🐞 BugFix, 🔨 Refactor

#279 Add File 'View NoticeList for Driver Controller' And View DriverDashboard DeliveryList
  src/main/java/com/akatsuki/pioms/dashboard/aggregate/ResponseDriverDashBoard.java
  src/main/java/com/akatsuki/pioms/dashboard/controller/DashboardController.java
  src/main/java/com/akatsuki/pioms/dashboard/service/DashboardService.java
  src/main/java/com/akatsuki/pioms/dashboard/service/DashboardServiceImpl.java
  src/main/java/com/akatsuki/pioms/invoice/dto/InvoiceDTO.java
  src/main/java/com/akatsuki/pioms/invoice/repository/InvoiceRepository.java
  src/main/java/com/akatsuki/pioms/invoice/service/InvoiceService.java
  src/main/java/com/akatsuki/pioms/invoice/service/InvoiceServiceImpl.java
  src/main/java/com/akatsuki/pioms/notice/controller/NoticeDriverController.java
  src/main/java/com/akatsuki/pioms/order/dto/OrderDTO.java
  src/main/java/com/akatsuki/pioms/order/repository/OrderRepository.java
  src/main/java/com/akatsuki/pioms/order/service/OrderService.java
  src/main/java/com/akatsuki/pioms/order/service/OrderServiceImpl.java
Labels: ✨ Feature, 🔨 Refactor

#290 Refactor: refactoring FranchiseWarehouse BE
  src/main/java/com/akatsuki/pioms/franchise/repository/FranchiseRepository.java
  src/main/java/com/akatsuki/pioms/frwarehouse/controller/franchiseWarehouseController.java
  src/main/java/com/akatsuki/pioms/frwarehouse/repository/FranchiseWarehouseRepository.java
  src/main/java/com/akatsuki/pioms/frwarehouse/service/FranchiseWarehouseService.java
  src/main/java/com/akatsuki/pioms/frwarehouse/service/FranchiseWarehouseServiceImpl.java
Labels: ✨ Feature, 🔨 Refactor

#291 ExcelDownload Admins,Drivers,Requests and so on + PDF download for Manuals
  build.gradle
  src/main/java/com/akatsuki/pioms/config/SecurityConfig.java
  src/main/java/com/akatsuki/pioms/excel/admin/AdminExcelController.java
  src/main/java/com/akatsuki/pioms/excel/admin/AdminManualPDFController.java
  src/main/java/com/akatsuki/pioms/excel/admin/DriverExcelController.java
  src/main/java/com/akatsuki/pioms/excel/admin/FrOwnerExcelController.java
  src/main/java/com/akatsuki/pioms/excel/admin/FranchiseExcelController.java
  src/main/java/com/akatsuki/pioms/excel/admin/LogExcelController.java
  src/main/java/com/akatsuki/pioms/excel/admin/ProductExcelAdminController.java
  src/main/java/com/akatsuki/pioms/excel/driver/DriverManualPDFController.java
  src/main/java/com/akatsuki/pioms/excel/franchise/ExchangeExcelController.java
  src/main/java/com/akatsuki/pioms/excel/franchise/FrOwnerManualPDFController.java
  src/main/java/com/akatsuki/pioms/excel/franchise/ProductExcelFranchiseController.java
  src/main/java/com/akatsuki/pioms/excel/franchise/RequestExcelController.java
  src/main/java/com/akatsuki/pioms/frowner/dto/FranchiseOwnerDTO.java
  src/main/java/com/akatsuki/pioms/order/controller/FranchiseOrderController.java
Labels: ✨ Feature, 📬 API

#292 fix,feat: add adminPhone in orderDTO, change order url, add update Product with image logic
  src/main/java/com/akatsuki/pioms/order/aggregate/OrderVO.java
  src/main/java/com/akatsuki/pioms/order/controller/AdminOrderController.java
  src/main/java/com/akatsuki/pioms/order/dto/OrderDTO.java
  src/main/java/com/akatsuki/pioms/product/controller/AdminProductController.java
  src/main/java/com/akatsuki/pioms/product/service/ProductService.java
  src/main/java/com/akatsuki/pioms/product/service/ProductServiceImpl.java
Labels: 🐞 BugFix, ✨ Feature, 🔨 Refactor

#293 fix: fix image change
  src/main/java/com/akatsuki/pioms/image/service/ImageService.java
  src/main/java/com/akatsuki/pioms/product/service/ProductServiceImpl.java
Labels: 🐞 BugFix

#295 create method for favoriteByFranchiseOwner, dashBoard for franchiseOwner , refacotring orderStat, orderRepository
  src/main/java/com/akatsuki/pioms/dashboard/aggregate/ResponseFranchiseDashBoard.java
  src/main/java/com/akatsuki/pioms/dashboard/controller/DashboardController.java
  src/main/java/com/akatsuki/pioms/dashboard/service/DashboardService.java
  src/main/java/com/akatsuki/pioms/dashboard/service/DashboardServiceImpl.java
  src/main/java/com/akatsuki/pioms/frowner/dto/FranchiseOwnerDTO.java
  src/main/java/com/akatsuki/pioms/frwarehouse/controller/franchiseWarehouseController.java
  src/main/java/com/akatsuki/pioms/frwarehouse/repository/FranchiseWarehouseRepository.java
  src/main/java/com/akatsuki/pioms/frwarehouse/service/FranchiseWarehouseService.java
  src/main/java/com/akatsuki/pioms/frwarehouse/service/FranchiseWarehouseServiceImpl.java
  src/main/java/com/akatsuki/pioms/order/aggregate/OrderStat.java
  src/main/java/com/akatsuki/pioms/order/repository/OrderRepository.java
Labels: ✨ Feature, 🔨 Refactor

#296 update product with image
  src/main/java/com/akatsuki/pioms/product/controller/AdminProductController.java
Labels: ✨ Feature, 📬 API

#297 Franchise owner KakaoTalk notification function for products out of stock
  build.gradle
  src/main/java/com/akatsuki/pioms/frwarehouse/aggregate/FranchiseWarehouse.java
  src/main/java/com/akatsuki/pioms/frwarehouse/controller/franchiseWarehouseController.java
  src/main/java/com/akatsuki/pioms/frwarehouse/service/FranchiseWarehouseService.java
  src/main/java/com/akatsuki/pioms/frwarehouse/service/FranchiseWarehouseServiceImpl.java
  src/main/java/com/akatsuki/pioms/product/service/ProductServiceImpl.java
Labels: 🐞 BugFix, ✨ Feature, 🔨 Refactor

#298 fix: change exchange controller url
  src/main/java/com/akatsuki/pioms/exchange/controller/AdminExchangeController.java
  src/main/java/com/akatsuki/pioms/exchange/controller/FranchiseExchangeController.java
  src/main/java/com/akatsuki/pioms/frwarehouse/controller/franchiseWarehouseController.java
  src/main/java/com/akatsuki/pioms/frwarehouse/dto/FranchiseWarehouseDTO.java
  src/main/java/com/akatsuki/pioms/order/aggregate/RequestPutOrder.java
  src/main/java/com/akatsuki/pioms/order/service/OrderServiceImpl.java
Labels: 🐞 BugFix

#303 Refactoring of all managers and franchise owners
  src/main/java/com/akatsuki/pioms/admin/aggregate/Admin.java
  src/main/java/com/akatsuki/pioms/admin/controller/AdminInfoController.java
  src/main/java/com/akatsuki/pioms/admin/dto/AdminDTO.java
  src/main/java/com/akatsuki/pioms/admin/repository/AdminRepository.java
  src/main/java/com/akatsuki/pioms/admin/service/AdminInfoService.java
  src/main/java/com/akatsuki/pioms/admin/service/AdminInfoServiceImpl.java
  src/main/java/com/akatsuki/pioms/excel/admin/FrOwnerExcelController.java
  src/main/java/com/akatsuki/pioms/frowner/aggregate/FranchiseOwner.java
  src/main/java/com/akatsuki/pioms/frowner/controller/AdminOnlyFrOwnerController.java
  src/main/java/com/akatsuki/pioms/frowner/controller/FrOwnerOnlyFrOwnerController.java
  src/main/java/com/akatsuki/pioms/frowner/dto/FranchiseOwnerDTO.java
  src/main/java/com/akatsuki/pioms/frowner/service/FranchiseOwnerService.java
  src/main/java/com/akatsuki/pioms/frowner/service/FranchiseOwnerServiceImpl.java
Labels: 🐞 BugFix, ✨ Feature, 🔨 Refactor

#304 Delivery driver and franchise refactoring
  src/main/java/com/akatsuki/pioms/dashboard/aggregate/ResponseAdminDashBoard.java
  src/main/java/com/akatsuki/pioms/dashboard/service/DashboardServiceImpl.java
  src/main/java/com/akatsuki/pioms/driver/aggregate/DeliveryDriver.java
  src/main/java/com/akatsuki/pioms/driver/controller/AdminOnlyDriverInfoController.java
  src/main/java/com/akatsuki/pioms/driver/controller/DriverOnlyDriverInfoController.java
  src/main/java/com/akatsuki/pioms/driver/dto/DeliveryDriverDTO.java
  src/main/java/com/akatsuki/pioms/driver/repository/DeliveryDriverRepository.java
  src/main/java/com/akatsuki/pioms/driver/service/DeliveryDriverService.java
  src/main/java/com/akatsuki/pioms/driver/service/DeliveryDriverServiceImpl.java
  src/main/java/com/akatsuki/pioms/excel/admin/DriverExcelController.java
  src/main/java/com/akatsuki/pioms/excel/admin/FranchiseExcelController.java
  src/main/java/com/akatsuki/pioms/franchise/aggregate/Franchise.java
  src/main/java/com/akatsuki/pioms/franchise/controller/AdminOnlyFranchiseController.java
  src/main/java/com/akatsuki/pioms/franchise/controller/FranchiseOnlyFranchiseController.java
  src/main/java/com/akatsuki/pioms/franchise/dto/FranchiseDTO.java
  src/main/java/com/akatsuki/pioms/franchise/repository/FranchiseRepository.java
  src/main/java/com/akatsuki/pioms/franchise/service/FranchiseService.java
  src/main/java/com/akatsuki/pioms/franchise/service/FranchiseServiceImpl.java
  src/main/java/com/akatsuki/pioms/frowner/dto/FranchiseOwnerDTO.java
  src/main/java/com/akatsuki/pioms/frwarehouse/service/FranchiseWarehouseServiceImpl.java
Labels: 🐞 BugFix, ✨ Feature, 🔨 Refactor

#306 Refactoring Add aggregate to orderDTO
  src/main/java/com/akatsuki/pioms/order/dto/OrderDTO.java
Labels: ✨ Feature, 🔨 Refactor

#308 Add dashboard service
  src/main/java/com/akatsuki/pioms/config/SecurityConfig.java
  src/main/java/com/akatsuki/pioms/dashboard/aggregate/ResponseAdminDashBoard.java
  src/main/java/com/akatsuki/pioms/dashboard/service/DashboardServiceImpl.java
  src/main/java/com/akatsuki/pioms/product/repository/ProductRepository.java
  src/main/java/com/akatsuki/pioms/product/service/ProductService.java
  src/main/java/com/akatsuki/pioms/product/service/ProductServiceImpl.java
Labels: 🐞 BugFix, 🔨 Refactor

#310 Process images by connecting s3 bucket
  .github/workflows/deploy.yml
  build.gradle
  src/main/java/com/akatsuki/pioms/image/service/ImageService.java
Labels: ⚙ Setting, 🌏 Deploy, ✨ Feature

#311 Refactor: refactoring ask BE
  src/main/java/com/akatsuki/pioms/ask/controller/AskFranchiseController.java
Labels: 🔨 Refactor

#312 FIX errors of order
  src/main/java/com/akatsuki/pioms/ask/dto/AskDTO.java
  src/main/java/com/akatsuki/pioms/notice/aggregate/NoticeVO.java
  src/main/java/com/akatsuki/pioms/order/aggregate/OrderStat.java
  src/main/java/com/akatsuki/pioms/order/controller/FranchiseOrderController.java
  src/main/java/com/akatsuki/pioms/order/service/AdminOrderFacade.java
  src/main/java/com/akatsuki/pioms/order/service/FranchiseOrderFacade.java
  src/main/java/com/akatsuki/pioms/order/service/OrderService.java
  src/main/java/com/akatsuki/pioms/order/service/OrderServiceImpl.java
  src/main/java/com/akatsuki/pioms/product/service/ProductService.java
  src/main/java/com/akatsuki/pioms/product/service/ProductServiceImpl.java
Labels: 🐞 BugFix, ✨ Feature

#315 insert url image view and category for franchise
  src/main/java/com/akatsuki/pioms/categoryFirst/controller/FrCategoryFirstController.java
  src/main/java/com/akatsuki/pioms/categorySecond/controller/FrCategorySecondController.java
  src/main/java/com/akatsuki/pioms/categoryThird/controller/FrCategoryThirdController.java
  src/main/java/com/akatsuki/pioms/product/controller/FrProductController.java
  src/test/java/com/akatsuki/pioms/categoryFirst/service/CategoryFirstServiceTest.java
Labels: ✨ Feature, 🔨 Refactor

#314 fix dashboard error, order dto error
  src/main/java/com/akatsuki/pioms/dashboard/controller/DashboardController.java
  src/main/java/com/akatsuki/pioms/dashboard/service/DashboardService.java
  src/main/java/com/akatsuki/pioms/dashboard/service/DashboardServiceImpl.java
  src/main/java/com/akatsuki/pioms/invoice/controller/AdminInvoiceController.java
  src/main/java/com/akatsuki/pioms/invoice/repository/InvoiceRepository.java
  src/main/java/com/akatsuki/pioms/invoice/service/InvoiceService.java
  src/main/java/com/akatsuki/pioms/invoice/service/InvoiceServiceImpl.java
  src/main/java/com/akatsuki/pioms/order/controller/AdminOrderController.java
  src/main/java/com/akatsuki/pioms/order/repository/OrderRepository.java
  src/main/java/com/akatsuki/pioms/order/service/OrderServiceImpl.java
Labels: 🐞 BugFix

#316 change: not enough cnt
  src/main/java/com/akatsuki/pioms/product/repository/ProductRepository.java
Labels: 🔨 Refactor

#318 Login Sign up and test environment settings
  .gitignore
  build.gradle
  src/main/java/com/akatsuki/pioms/admin/aggregate/Admin.java
  src/main/java/com/akatsuki/pioms/admin/service/AdminInfoServiceImpl.java
  src/main/java/com/akatsuki/pioms/config/RedisConfig.java
  src/main/java/com/akatsuki/pioms/config/SecurityConfig.java
  src/main/java/com/akatsuki/pioms/log/etc/LogStatus.java
  src/main/java/com/akatsuki/pioms/login/controller/LoginController.java
  src/main/java/com/akatsuki/pioms/login/service/LoginService.java
  src/main/java/com/akatsuki/pioms/login/service/LoginServiceImpl.java
  src/test/java/com/akatsuki/pioms/PiomsBeApplicationTests.java
  src/test/java/com/akatsuki/pioms/admin/service/AdminInfoServiceTest.java
  src/test/java/com/akatsuki/pioms/config/MockRedisConfig.java
Labels: ⚙ Setting, 🐞 BugFix, ✨ Feature, 🔨 Refactor, ✅ Test

#319 build file -> gradle, deploy.yml test env setting
  .github/workflows/deploy.yml
  build.gradle
Labels: ⚙ Setting

#320 TestCode of Categories
  src/main/java/com/akatsuki/pioms/categoryFirst/dto/CategoryFirstCreateDTO.java
  src/main/java/com/akatsuki/pioms/categoryFirst/dto/CategoryFirstUpdateDTO.java
  src/main/java/com/akatsuki/pioms/categoryFirst/service/CategoryFirstService.java
  src/main/java/com/akatsuki/pioms/categoryFirst/service/CategoryFirstServiceImpl.java
  src/main/java/com/akatsuki/pioms/categorySecond/dto/CategorySecondCreateDTO.java
  src/main/java/com/akatsuki/pioms/categorySecond/dto/CategorySecondUpdateDTO.java
  src/main/java/com/akatsuki/pioms/categorySecond/service/CategorySecondService.java
  src/main/java/com/akatsuki/pioms/categorySecond/service/CategorySecondServiceImpl.java
  src/main/java/com/akatsuki/pioms/categoryThird/dto/CategoryThirdCreateDTO.java
  src/main/java/com/akatsuki/pioms/categoryThird/dto/CategoryThirdUpdateDTO.java
  src/main/java/com/akatsuki/pioms/categoryThird/service/CategoryThirdService.java
  src/main/java/com/akatsuki/pioms/categoryThird/service/CategoryThirdServiceImpl.java
  src/main/java/com/akatsuki/pioms/product/dto/ProductCreateDTO.java
  src/main/java/com/akatsuki/pioms/product/dto/ProductUpdateDTO.java
  src/main/java/com/akatsuki/pioms/product/service/ProductService.java
  src/main/java/com/akatsuki/pioms/product/service/ProductServiceImpl.java
  src/test/java/com/akatsuki/pioms/admin/service/AdminInfoServiceTest.java
  src/test/java/com/akatsuki/pioms/ask/service/AskServiceTests.java
  src/test/java/com/akatsuki/pioms/categoryFirst/service/CategoryFirstServiceTest.java
  src/test/java/com/akatsuki/pioms/categorySecond/service/CategorySecondServiceTest.java
  src/test/java/com/akatsuki/pioms/categoryThird/service/CategoryThirdServiceTest.java
  src/test/java/com/akatsuki/pioms/product/service/ProductServiceTest.java
Labels: ✅ Test

#321 Create TestCode for Ask, Favoirte, and Log
  src/test/java/com/akatsuki/pioms/ask/service/AskServiceTests.java
  src/test/java/com/akatsuki/pioms/frwarehouse/service/FranchiseWarehouseServiceTest.java
  src/test/java/com/akatsuki/pioms/log/service/LogServiceImplTest.java
Labels: ✅ Test

#322 Test of Order,Exchange,Invoice
  src/main/java/com/akatsuki/pioms/exchange/controller/AdminExchangeController.java
  src/main/java/com/akatsuki/pioms/exchange/controller/FranchiseExchangeController.java
  src/main/java/com/akatsuki/pioms/exchange/service/ExchangeServiceImpl.java
  src/main/java/com/akatsuki/pioms/invoice/controller/AdminInvoiceController.java
  src/main/java/com/akatsuki/pioms/invoice/controller/FranchiseInvoiceController.java
  src/main/java/com/akatsuki/pioms/invoice/dto/InvoiceDTO.java
  src/main/java/com/akatsuki/pioms/invoice/service/InvoiceServiceImpl.java
  src/main/java/com/akatsuki/pioms/order/aggregate/Order.java
  src/main/java/com/akatsuki/pioms/order/controller/FranchiseOrderController.java
  src/main/java/com/akatsuki/pioms/order/dto/OrderDTO.java
  src/main/java/com/akatsuki/pioms/order/service/OrderServiceImpl.java
  src/main/java/com/akatsuki/pioms/product/dto/ProductDTO.java
  src/test/java/com/akatsuki/pioms/exchange/service/ExchangeServiceTest.java
  src/test/java/com/akatsuki/pioms/invoice/service/InvoiceServiceTest.java
  src/test/java/com/akatsuki/pioms/order/service/OrderFacadeTest.java
  src/test/java/com/akatsuki/pioms/order/service/OrderServiceImplTest.java
  src/test/java/com/akatsuki/pioms/ordertest.java
Labels: ✅ Test

#325 Fix Role, Role Hierarchy
  src/main/java/com/akatsuki/pioms/config/SecurityConfig.java
Labels: 🔨 Refactor

#326 Improved query filtering and logout
  src/main/java/com/akatsuki/pioms/config/SecurityConfig.java
  src/main/java/com/akatsuki/pioms/dashboard/service/DashboardServiceImpl.java
  src/main/java/com/akatsuki/pioms/driver/dto/DeliveryDriverDTO.java
  src/main/java/com/akatsuki/pioms/franchise/controller/AdminOnlyFranchiseController.java
  src/main/java/com/akatsuki/pioms/franchise/service/FranchiseService.java
  src/main/java/com/akatsuki/pioms/franchise/service/FranchiseServiceImpl.java
  src/main/java/com/akatsuki/pioms/frowner/controller/AdminOnlyFrOwnerController.java
  src/main/java/com/akatsuki/pioms/frowner/repository/FranchiseOwnerRepository.java
  src/main/java/com/akatsuki/pioms/frowner/service/FranchiseOwnerServiceImpl.java
  src/main/java/com/akatsuki/pioms/jwt/CustomLogoutFilter.java
  src/main/java/com/akatsuki/pioms/user/dto/CustomUserDetails.java
  src/main/java/com/akatsuki/pioms/user/service/CustomUserDetailsService.java
Labels: 🐞 BugFix, ✨ Feature, 🔨 Refactor

#327 Fix: edit security config file
  src/main/java/com/akatsuki/pioms/config/SecurityConfig.java
  src/main/java/com/akatsuki/pioms/dashboard/controller/DashboardController.java
  src/test/java/com/akatsuki/pioms/notice/service/NoticeServiceTest.java
Labels: 🔨 Refactor

#330 Modify Code about Franchise
  src/main/java/com/akatsuki/pioms/excel/admin/AdminManualPDFController.java
  src/main/java/com/akatsuki/pioms/excel/admin/RootManualPDFController.java
  src/main/java/com/akatsuki/pioms/excel/driver/DriverManualPDFController.java
  src/main/java/com/akatsuki/pioms/excel/franchise/FrOwnerManualPDFController.java
  src/main/java/com/akatsuki/pioms/franchise/aggregate/Franchise.java
  src/main/java/com/akatsuki/pioms/franchise/controller/AdminOnlyFranchiseController.java
  src/main/java/com/akatsuki/pioms/franchise/controller/FranchiseOnlyFranchiseController.java
  src/main/java/com/akatsuki/pioms/franchise/dto/FranchiseDTO.java
  src/main/java/com/akatsuki/pioms/franchise/service/FranchiseService.java
  src/main/java/com/akatsuki/pioms/franchise/service/FranchiseServiceImpl.java
  src/test/java/com/akatsuki/pioms/admin/service/AdminInfoServiceTest.java
  src/test/java/com/akatsuki/pioms/categoryThird/service/CategoryThirdServiceTest.java
  src/test/java/com/akatsuki/pioms/product/service/ProductServiceTest.java
Labels: ✨ Feature, 🔨 Refactor

#329 Refactoring View InvoiceDetail DriverCode
  src/main/java/com/akatsuki/pioms/exchange/repository/ExchangeRepository.java
  src/main/java/com/akatsuki/pioms/exchange/service/ExchangeService.java
  src/main/java/com/akatsuki/pioms/exchange/service/ExchangeServiceImpl.java
  src/main/java/com/akatsuki/pioms/invoice/aggregate/ResponseInvoiceDetail.java
  src/main/java/com/akatsuki/pioms/invoice/service/InvoiceServiceImpl.java
  src/main/java/com/akatsuki/pioms/order/dto/OrderProductDTO.java
Labels: ✨ Feature, 🔨 Refactor

#331 Feature/order
  src/main/java/com/akatsuki/pioms/config/SecurityConfig.java
  src/main/java/com/akatsuki/pioms/dashboard/service/DashboardServiceImpl.java
  src/main/java/com/akatsuki/pioms/excel/franchise/RequestExcelController.java
Labels: 🔨 Refactor

#332 fix error, swagger
  src/main/java/com/akatsuki/pioms/admin/controller/AdminInfoController.java
  src/main/java/com/akatsuki/pioms/ask/controller/AskAdminController.java
  src/main/java/com/akatsuki/pioms/ask/controller/AskFranchiseController.java
  src/main/java/com/akatsuki/pioms/categoryFirst/controller/CategoryFirstController.java
  src/main/java/com/akatsuki/pioms/categoryFirst/controller/FrCategoryFirstController.java
  src/main/java/com/akatsuki/pioms/categorySecond/controller/CategorySecondController.java
  src/main/java/com/akatsuki/pioms/categorySecond/controller/FrCategorySecondController.java
  src/main/java/com/akatsuki/pioms/categoryThird/controller/CategoryThirdController.java
  src/main/java/com/akatsuki/pioms/categoryThird/controller/FrCategoryThirdController.java
  src/main/java/com/akatsuki/pioms/company/controller/CompanyController.java
  src/main/java/com/akatsuki/pioms/dashboard/controller/DashboardController.java
  src/main/java/com/akatsuki/pioms/driver/controller/AdminOnlyDriverInfoController.java
  src/main/java/com/akatsuki/pioms/driver/controller/DriverOnlyDriverInfoController.java
  src/main/java/com/akatsuki/pioms/excel/admin/AdminExcelController.java
  src/main/java/com/akatsuki/pioms/excel/admin/AdminManualPDFController.java
  src/main/java/com/akatsuki/pioms/excel/admin/DriverExcelController.java
  src/main/java/com/akatsuki/pioms/excel/admin/FrOwnerExcelController.java
  src/main/java/com/akatsuki/pioms/excel/admin/FranchiseExcelController.java
  src/main/java/com/akatsuki/pioms/excel/admin/LogExcelController.java
  src/main/java/com/akatsuki/pioms/excel/admin/ProductExcelAdminController.java
  src/main/java/com/akatsuki/pioms/excel/admin/RootManualPDFController.java
  src/main/java/com/akatsuki/pioms/excel/driver/DriverManualPDFController.java
  src/main/java/com/akatsuki/pioms/excel/franchise/ExchangeExcelController.java
  src/main/java/com/akatsuki/pioms/excel/franchise/FrOwnerManualPDFController.java
  src/main/java/com/akatsuki/pioms/excel/franchise/ProductExcelFranchiseController.java
  src/main/java/com/akatsuki/pioms/excel/franchise/RequestExcelController.java
  src/main/java/com/akatsuki/pioms/exchange/controller/AdminExchangeController.java
  src/main/java/com/akatsuki/pioms/exchange/controller/FranchiseExchangeController.java
  src/main/java/com/akatsuki/pioms/franchise/controller/AdminOnlyFranchiseController.java
  src/main/java/com/akatsuki/pioms/franchise/controller/FranchiseOnlyFranchiseController.java
  src/main/java/com/akatsuki/pioms/franchise/dto/FranchiseDTO.java
  src/main/java/com/akatsuki/pioms/franchise/service/FranchiseService.java
  src/main/java/com/akatsuki/pioms/franchise/service/FranchiseServiceImpl.java
  src/main/java/com/akatsuki/pioms/frowner/controller/AdminOnlyFrOwnerController.java
  src/main/java/com/akatsuki/pioms/frowner/controller/FrOwnerOnlyFrOwnerController.java
  src/main/java/com/akatsuki/pioms/frwarehouse/controller/franchiseWarehouseController.java
  src/main/java/com/akatsuki/pioms/invoice/controller/AdminInvoiceController.java
  src/main/java/com/akatsuki/pioms/invoice/controller/DriverInvoiceController.java
  src/main/java/com/akatsuki/pioms/invoice/controller/FranchiseInvoiceController.java
  src/main/java/com/akatsuki/pioms/log/controller/LogController.java
  src/main/java/com/akatsuki/pioms/login/controller/LoginController.java
  src/main/java/com/akatsuki/pioms/login/controller/ReissueController.java
  src/main/java/com/akatsuki/pioms/notice/controller/NoticeAdminController.java
  src/main/java/com/akatsuki/pioms/notice/controller/NoticeDriverController.java
  src/main/java/com/akatsuki/pioms/notice/controller/NoticeFranchiseController.java
  src/main/java/com/akatsuki/pioms/order/controller/AdminOrderController.java
  src/main/java/com/akatsuki/pioms/order/controller/FranchiseOrderController.java
  src/main/java/com/akatsuki/pioms/product/controller/AdminProductController.java
  src/main/java/com/akatsuki/pioms/product/controller/FrProductController.java
  src/main/java/com/akatsuki/pioms/specs/controller/AdminSpecsController.java
  src/main/java/com/akatsuki/pioms/specs/controller/FranchiseSpecsController.java
Labels: 📃 Docs

#333 Temporarily resolved JWT token issue and security issue
  src/main/java/com/akatsuki/pioms/admin/controller/AdminInfoController.java
  src/main/java/com/akatsuki/pioms/admin/service/AdminInfoService.java
  src/main/java/com/akatsuki/pioms/admin/service/AdminInfoServiceImpl.java
  src/main/java/com/akatsuki/pioms/config/SecurityConfig.java
  src/main/java/com/akatsuki/pioms/franchise/dto/FranchiseDTO.java
  src/main/java/com/akatsuki/pioms/franchise/repository/FranchiseRepository.java
  src/main/java/com/akatsuki/pioms/frowner/service/FranchiseOwnerServiceImpl.java
  src/main/java/com/akatsuki/pioms/jwt/LoginFilter.java
  src/main/java/com/akatsuki/pioms/login/service/LoginServiceImpl.java
Labels: ⚙ Setting, 🐞 BugFix, 🔨 Refactor

#334 Refactor: refactoring Favorite Test Code
  src/test/java/com/akatsuki/pioms/frwarehouse/service/FranchiseWarehouseServiceTest.java
Labels: 🔨 Refactor, ✅ Test

#335 Feature/product
  src/main/java/com/akatsuki/pioms/excel/admin/FranchiseExcelController.java
  src/main/java/com/akatsuki/pioms/franchise/service/FranchiseServiceImpl.java
Labels: 🐞 BugFix, 🔨 Refactor, 📬 API

#336 Feature/user
  src/main/java/com/akatsuki/pioms/driver/aggregate/DeliveryDriver.java
  src/main/java/com/akatsuki/pioms/driver/dto/DeliveryDriverDTO.java
  src/main/java/com/akatsuki/pioms/driver/service/DeliveryDriverServiceImpl.java
Labels: 🐞 BugFix, 🔨 Refactor

#338 Code fix for excel and auto-paging for PDFs
  src/main/java/com/akatsuki/pioms/excel/admin/AdminManualPDFController.java
  src/main/java/com/akatsuki/pioms/excel/admin/ProductExcelAdminController.java
  src/main/java/com/akatsuki/pioms/excel/admin/RootManualPDFController.java
  src/main/java/com/akatsuki/pioms/excel/driver/DriverManualPDFController.java
  src/main/java/com/akatsuki/pioms/excel/franchise/FrOwnerManualPDFController.java
  src/main/java/com/akatsuki/pioms/excel/franchise/ProductExcelFranchiseController.java
Labels: 🐞 BugFix, 🔨 Refactor, 📬 API

#339 User and franchise inquiry DESC processing completed
  src/main/java/com/akatsuki/pioms/admin/repository/AdminRepository.java
  src/main/java/com/akatsuki/pioms/admin/service/AdminInfoServiceImpl.java
  src/main/java/com/akatsuki/pioms/driver/repository/DeliveryDriverRepository.java
  src/main/java/com/akatsuki/pioms/driver/service/DeliveryDriverServiceImpl.java
  src/main/java/com/akatsuki/pioms/franchise/repository/FranchiseRepository.java
  src/main/java/com/akatsuki/pioms/franchise/service/FranchiseServiceImpl.java
  src/main/java/com/akatsuki/pioms/frowner/repository/FranchiseOwnerRepository.java
  src/main/java/com/akatsuki/pioms/frowner/service/FranchiseOwnerServiceImpl.java
  src/test/java/com/akatsuki/pioms/admin/service/AdminInfoServiceTest.java
Labels: 🔨 Refactor

#340 Show exchanges desc, add check root logic in GetUserInfo class
  src/main/java/com/akatsuki/pioms/config/GetUserInfo.java
  src/main/java/com/akatsuki/pioms/exchange/controller/AdminExchangeController.java
  src/main/java/com/akatsuki/pioms/exchange/repository/ExchangeRepository.java
  src/main/java/com/akatsuki/pioms/exchange/service/ExchangeService.java
  src/main/java/com/akatsuki/pioms/exchange/service/ExchangeServiceImpl.java
  src/main/java/com/akatsuki/pioms/invoice/service/InvoiceServiceImpl.java
Labels: 🐞 BugFix, 🔨 Refactor

#341 Change log date form
  src/main/java/com/akatsuki/pioms/excel/admin/LogExcelController.java
Labels: 🐞 BugFix, 🔨 Refactor

#342 hot-fix: fix get exchange list
  src/main/java/com/akatsuki/pioms/exchange/service/ExchangeServiceImpl.java
Labels: 🐞 BugFix

#343 fix found error of orderDTO
  src/main/java/com/akatsuki/pioms/order/dto/OrderDTO.java
Labels: 🔨 Refactor

#345 'Develop' into 'main'
  .github/workflows/deploy.yml
  build.gradle
  src/main/java/com/akatsuki/pioms/admin/repository/AdminRepository.java
  src/main/java/com/akatsuki/pioms/admin/service/AdminInfoServiceImpl.java
  src/main/java/com/akatsuki/pioms/config/CorsConfig.java
  src/main/java/com/akatsuki/pioms/config/GetUserInfo.java
  src/main/java/com/akatsuki/pioms/config/SecurityConfig.java
  src/main/java/com/akatsuki/pioms/driver/repository/DeliveryDriverRepository.java
  src/main/java/com/akatsuki/pioms/driver/service/DeliveryDriverServiceImpl.java
  src/main/java/com/akatsuki/pioms/excel/admin/AdminManualPDFController.java
  src/main/java/com/akatsuki/pioms/excel/admin/LogExcelController.java
  src/main/java/com/akatsuki/pioms/excel/admin/ProductExcelAdminController.java
  src/main/java/com/akatsuki/pioms/excel/admin/RootManualPDFController.java
  src/main/java/com/akatsuki/pioms/excel/driver/DriverManualPDFController.java
  src/main/java/com/akatsuki/pioms/excel/franchise/FrOwnerManualPDFController.java
  src/main/java/com/akatsuki/pioms/excel/franchise/ProductExcelFranchiseController.java
  src/main/java/com/akatsuki/pioms/exchange/controller/AdminExchangeController.java
  src/main/java/com/akatsuki/pioms/exchange/repository/ExchangeRepository.java
  src/main/java/com/akatsuki/pioms/exchange/service/ExchangeService.java
  src/main/java/com/akatsuki/pioms/exchange/service/ExchangeServiceImpl.java
  src/main/java/com/akatsuki/pioms/franchise/repository/FranchiseRepository.java
  src/main/java/com/akatsuki/pioms/franchise/service/FranchiseServiceImpl.java
  src/main/java/com/akatsuki/pioms/frowner/repository/FranchiseOwnerRepository.java
  src/main/java/com/akatsuki/pioms/frowner/service/FranchiseOwnerServiceImpl.java
  src/main/java/com/akatsuki/pioms/frwarehouse/service/FranchiseWarehouseServiceImpl.java
  src/main/java/com/akatsuki/pioms/invoice/service/InvoiceServiceImpl.java
  src/main/java/com/akatsuki/pioms/order/dto/OrderDTO.java
  src/main/java/com/akatsuki/pioms/order/service/OrderServiceImpl.java
  src/main/java/com/akatsuki/pioms/product/service/ProductServiceImpl.java
  src/test/java/com/akatsuki/pioms/admin/service/AdminInfoServiceTest.java
Labels: 🌏 Deploy
