Repository PI-Akatsuki/PIOMS.BE, pull requests merged in 2024-05, with the labels that each got.

#15 View All Category and view category by categoryCode
  build.gradle
  src/main/java/com/akatsuki/pioms/category/controller/CategoryFirstController.java
  src/main/java/com/akatsuki/pioms/category/controller/CategorySecondController.java
  src/main/java/com/akatsuki/pioms/category/controller/CategoryThirdController.java
  src/main/java/com/akatsuki/pioms/category/entity/CategoryFirst.java
  src/main/java/com/akatsuki/pioms/category/entity/CategorySecond.java
  src/main/java/com/akatsuki/pioms/category/entity/CategoryThird.java
  src/main/java/com/akatsuki/pioms/category/repository/CategoryFirstDAO.java
  src/main/java/com/akatsuki/pioms/category/repository/CategorySecondDAO.java
  src/main/java/com/akatsuki/pioms/category/repository/CategoryThirdDAO.java
  src/main/java/com/akatsuki/pioms/category/service/CategoryFirstService.java
  src/main/java/com/akatsuki/pioms/category/service/CategoryFirstServiceImpl.java
  src/main/java/com/akatsuki/pioms/category/service/CategorySecondService.java
  src/main/java/com/akatsuki/pioms/category/service/CategorySecondServiceImpl.java
  src/main/java/com/akatsuki/pioms/category/service/CategoryThirdService.java
  src/main/java/com/akatsuki/pioms/category/service/CategoryThirdServiceImpl.java
  src/main/java/com/akatsuki/pioms/category/vo/RequestCategoryPost.java
  src/main/java/com/akatsuki/pioms/category/vo/ResponseCategoryPost.java
Labels: enhancement

#17 Create and Update CategoryThird
  src/main/java/com/akatsuki/pioms/category/controller/CategoryThirdController.java
  src/main/java/com/akatsuki/pioms/category/service/CategoryThirdService.java
  src/main/java/com/akatsuki/pioms/category/service/CategoryThirdServiceImpl.java
  src/main/java/com/akatsuki/pioms/category/vo/RequestCategoryUpdate.java
Labels: enhancement

#23 Vew Company information
  build.gradle
  src/main/java/com/akatsuki/pioms/company/controller/CompanyController.java
  src/main/java/com/akatsuki/pioms/company/dto/CompanyDTO.java
  src/main/java/com/akatsuki/pioms/company/entity/CompanyEntity.java
  src/main/java/com/akatsuki/pioms/company/repository/CompanyRepository.java
  src/main/java/com/akatsuki/pioms/company/service/CompanyService.java
  src/main/java/com/akatsuki/pioms/company/service/CompanyServiceImpl.java
  src/main/java/com/akatsuki/pioms/company/vo/CompanyVO.java
  src/main/java/com/akatsuki/pioms/config/ModelMapperConfig.java
Labels: enhancement

#24 View All Product
  src/main/java/com/akatsuki/pioms/category/entity/CategoryFirst.java
  src/main/java/com/akatsuki/pioms/category/entity/CategorySecond.java
  src/main/java/com/akatsuki/pioms/category/entity/CategoryThird.java
  src/main/java/com/akatsuki/pioms/category/repository/CategoryThirdDAO.java
  src/main/java/com/akatsuki/pioms/product/controller/ProductController.java
  src/main/java/com/akatsuki/pioms/product/entity/Product.java
  src/main/java/com/akatsuki/pioms/product/etc/PRODUCT_COLOR.java
  src/main/java/com/akatsuki/pioms/product/etc/PRODUCT_GENDER.java
  src/main/java/com/akatsuki/pioms/product/etc/PRODUCT_STATUS.java
  src/main/java/com/akatsuki/pioms/product/repository/ProductDAO.java
  src/main/java/com/akatsuki/pioms/product/service/ProductService.java
  src/main/java/com/akatsuki/pioms/product/service/ProductServiceImpl.java
Labels: enhancement

#28 Create new Product
  src/main/java/com/akatsuki/pioms/product/controller/ProductController.java
  src/main/java/com/akatsuki/pioms/product/entity/Product.java
  src/main/java/com/akatsuki/pioms/product/service/ProductService.java
  src/main/java/com/akatsuki/pioms/product/service/ProductServiceImpl.java
  src/main/java/com/akatsuki/pioms/product/vo/RequestProductPost.java
  src/main/java/com/akatsuki/pioms/product/vo/ResponseProductPost.java
Labels: enhancement

#33 Implementation of order, invoice, specs and exchange.
  src/main/java/com/akatsuki/pioms/event/OrderEvent.java
  src/main/java/com/akatsuki/pioms/exchange/controller/ExchangeController.java
  src/main/java/com/akatsuki/pioms/exchange/dto/ExchangeDTO.java
  src/main/java/com/akatsuki/pioms/exchange/entity/EXCHANGE_PRODUCT_STATUS.java
  src/main/java/com/akatsuki/pioms/exchange/entity/EXCHANGE_STATUS.java
  src/main/java/com/akatsuki/pioms/exchange/entity/ExchangeEntity.java
  src/main/java/com/akatsuki/pioms/exchange/entity/ExchangeProductEntity.java
  src/main/java/com/akatsuki/pioms/exchange/entity/RequestExchange.java
  src/main/java/com/akatsuki/pioms/exchange/repository/ExchangeProductRepository.java
  src/main/java/com/akatsuki/pioms/exchange/repository/ExchangeRepository.java
  src/main/java/com/akatsuki/pioms/exchange/service/ExchangeService.java
  src/main/java/com/akatsuki/pioms/exchange/service/ExchangeServiceImpl.java
  src/main/java/com/akatsuki/pioms/exchange/vo/ExchangeProductVO.java
  src/main/java/com/akatsuki/pioms/exchange/vo/ResponseExchange.java
  src/main/java/com/akatsuki/pioms/franchise/etc/DELIVERY_DATE.java
  src/main/java/com/akatsuki/pioms/invoice/controller/InvoiceController.java
  src/main/java/com/akatsuki/pioms/invoice/dto/InvoiceDTO.java
  src/main/java/com/akatsuki/pioms/invoice/entity/InvoiceEntity.java
  src/main/java/com/akatsuki/pioms/invoice/etc/DELIVERY_STATUS.java
  src/main/java/com/akatsuki/pioms/invoice/repository/InvoiceRepository.java
  src/main/java/com/akatsuki/pioms/invoice/service/InvoiceService.java
  src/main/java/com/akatsuki/pioms/invoice/service/InvoiceServiceImpl.java
  src/main/java/com/akatsuki/pioms/invoice/vo/OrderProductVO.java
  src/main/java/com/akatsuki/pioms/invoice/vo/ResponseInvoice.java
  src/main/java/com/akatsuki/pioms/invoice/vo/ResponseInvoiceList.java
  src/main/java/com/akatsuki/pioms/order/controller/OrderController.java
  src/main/java/com/akatsuki/pioms/order/dto/OrderDTO.java
  src/main/java/com/akatsuki/pioms/order/entity/OrderEntity.java
  src/main/java/com/akatsuki/pioms/order/entity/OrderProductEntity.java
  src/main/java/com/akatsuki/pioms/order/etc/ORDER_CONDITION.java
  src/main/java/com/akatsuki/pioms/order/repository/OrderProductRepository.java
  src/main/java/com/akatsuki/pioms/order/repository/OrderRepository.java
  src/main/java/com/akatsuki/pioms/order/service/OrderService.java
  src/main/java/com/akatsuki/pioms/order/service/OrderServiceImpl.java
  src/main/java/com/akatsuki/pioms/order/vo/OrderListVO.java
  src/main/java/com/akatsuki/pioms/order/vo/OrderVO.java
  src/main/java/com/akatsuki/pioms/order/vo/RequestOrderVO.java
  src/main/java/com/akatsuki/pioms/product/entity/ProductEntity.java
  src/main/java/com/akatsuki/pioms/product/repository/ProductRepository.java
  src/main/java/com/akatsuki/pioms/product/service/ProductService.java
  src/main/java/com/akatsuki/pioms/product/service/ProductServiceImpl.java
  src/main/java/com/akatsuki/pioms/specs/controller/ResponseSpecs.java
  src/main/java/com/akatsuki/pioms/specs/controller/SpecsController.java
  src/main/java/com/akatsuki/pioms/specs/entity/SpecsEntity.java
  src/main/java/com/akatsuki/pioms/specs/repository/SpecsRepository.java
  src/main/java/com/akatsuki/pioms/specs/service/SpecsService.java
  src/main/java/com/akatsuki/pioms/specs/service/SpecsServiceImpl.java
  src/test/java/com/akatsuki/pioms/exchange/service/ExchangeServiceImplTest.java
Labels: enhancement

#36 Build MariaDB Driver
  src/main/java/com/akatsuki/pioms/category/controller/CategoryThirdController.java
  src/main/java/com/akatsuki/pioms/category/repository/CategoryFirstRepository.java
  src/main/java/com/akatsuki/pioms/category/repository/CategorySecondRepository.java
  src/main/java/com/akatsuki/pioms/category/repository/CategoryThirdRepository.java
  src/main/java/com/akatsuki/pioms/category/service/CategoryFirstServiceImpl.java
  src/main/java/com/akatsuki/pioms/category/service/CategorySecondServiceImpl.java
  src/main/java/com/akatsuki/pioms/category/service/CategoryThirdService.java
  src/main/java/com/akatsuki/pioms/category/service/CategoryThirdServiceImpl.java
  src/main/java/com/akatsuki/pioms/product/controller/ProductController.java
  src/main/java/com/akatsuki/pioms/product/repository/ProductDAO.java
  src/main/java/com/akatsuki/pioms/product/repository/ProductRepository.java
  src/main/java/com/akatsuki/pioms/product/service/ProductService.java
  src/main/java/com/akatsuki/pioms/product/service/ProductServiceImpl.java
Labels: documentation

#37 Build MariaDB Driver
  build.gradle
Labels: documentation

#38 Create Ask Function(Admin, FranchiseOwner)
  src/main/java/com/akatsuki/pioms/ask/AskAdminController.java
  src/main/java/com/akatsuki/pioms/ask/AskFranchiseController.java
  src/main/java/com/akatsuki/pioms/ask/dto/AskCreateDTO.java
  src/main/java/com/akatsuki/pioms/ask/dto/AskDTO.java
  src/main/java/com/akatsuki/pioms/ask/dto/AskUpdateDTO.java
  src/main/java/com/akatsuki/pioms/ask/entity/AdminEntity.java
  src/main/java/com/akatsuki/pioms/ask/entity/AskEntity.java
  src/main/java/com/akatsuki/pioms/ask/entity/FranchiseOwnerEntity.java
  src/main/java/com/akatsuki/pioms/ask/etc/ADMIN_ROLE.java
  src/main/java/com/akatsuki/pioms/ask/etc/ASK_STATUS.java
  src/main/java/com/akatsuki/pioms/ask/repository/AdminRepository.java
  src/main/java/com/akatsuki/pioms/ask/repository/AskRepository.java
  src/main/java/com/akatsuki/pioms/ask/repository/FranchiseOwnerRepository.java
  src/main/java/com/akatsuki/pioms/ask/service/AskService.java
  src/main/java/com/akatsuki/pioms/ask/service/AskServiceImpl.java
  src/main/java/com/akatsuki/pioms/ask/vo/AskListVO.java
  src/main/java/com/akatsuki/pioms/ask/vo/AskVO.java
Labels: enhancement

#39 Implementation of Order, Invoice, Franchise, FranchiseWarehouse, Specs
  src/main/java/com/akatsuki/pioms/admin/entity/AdminEntity.java
  src/main/java/com/akatsuki/pioms/config/ModelMapperConfig.java
  src/main/java/com/akatsuki/pioms/event/OrderEvent.java
  src/main/java/com/akatsuki/pioms/exchange/service/ExchangeServiceImpl.java
  src/main/java/com/akatsuki/pioms/franchise/entity/FranchiseEntity.java
  src/main/java/com/akatsuki/pioms/franchise/entity/FranchiseOwnerEntity.java
  src/main/java/com/akatsuki/pioms/franchiseWarehouse/aggregate/FranchiseWarehouse.java
  src/main/java/com/akatsuki/pioms/franchiseWarehouse/controller/franchiseWarehouseController.java
  src/main/java/com/akatsuki/pioms/franchiseWarehouse/repository/FranchiseWarehouseRepository.java
  src/main/java/com/akatsuki/pioms/franchiseWarehouse/service/FranchiseWarehouseService.java
  src/main/java/com/akatsuki/pioms/franchiseWarehouse/service/FranchiseWarehouseServiceImpl.java
  src/main/java/com/akatsuki/pioms/invoice/controller/InvoiceController.java
  src/main/java/com/akatsuki/pioms/invoice/repository/InvoiceRepository.java
  src/main/java/com/akatsuki/pioms/invoice/service/InvoiceService.java
  src/main/java/com/akatsuki/pioms/invoice/service/InvoiceServiceImpl.java
  src/main/java/com/akatsuki/pioms/order/controller/AdminOrderController.java
  src/main/java/com/akatsuki/pioms/order/controller/FranchiseOrderController.java
  src/main/java/com/akatsuki/pioms/order/entity/OrderProductEntity.java
  src/main/java/com/akatsuki/pioms/order/repository/OrderProductRepository.java
  src/main/java/com/akatsuki/pioms/order/service/OrderService.java
  src/main/java/com/akatsuki/pioms/order/service/OrderServiceImpl.java
  src/main/java/com/akatsuki/pioms/order/vo/RequestPutOrder.java
  src/main/java/com/akatsuki/pioms/order/vo/RequestPutOrderCheck.java
  src/main/java/com/akatsuki/pioms/product/entity/Product.java
  src/main/java/com/akatsuki/pioms/product/entity/ProductEntity.java
  src/main/java/com/akatsuki/pioms/product/service/ProductServiceImpl.java
  src/main/java/com/akatsuki/pioms/specs/aggregate/ResponseSpecs.java
  src/main/java/com/akatsuki/pioms/specs/aggregate/SpecsEntity.java
  src/main/java/com/akatsuki/pioms/specs/controller/SpecsController.java
  src/main/java/com/akatsuki/pioms/specs/repository/SpecsRepository.java
  src/main/java/com/akatsuki/pioms/specs/service/SpecsService.java
  src/main/java/com/akatsuki/pioms/specs/service/SpecsServiceImpl.java
  src/main/java/com/akatsuki/pioms/testController.java
Labels: enhancement

#41 Company information inquiry and modification functions completed
  build.gradle
  src/main/java/com/akatsuki/pioms/company/aggregate/Company.java
  src/main/java/com/akatsuki/pioms/company/aggregate/CompanyVO.java
  src/main/java/com/akatsuki/pioms/company/controller/CompanyController.java
  src/main/java/com/akatsuki/pioms/company/repository/CompanyRepository.java
  src/main/java/com/akatsuki/pioms/company/service/CompanyService.java
  src/main/java/com/akatsuki/pioms/company/service/CompanyServiceImpl.java
Labels: enhancement

#46 Administrator full view detailed view function
  src/main/java/com/akatsuki/pioms/admin/aggregate/Admin.java
  src/main/java/com/akatsuki/pioms/admin/aggregate/AdminVO.java
  src/main/java/com/akatsuki/pioms/admin/controller/AdminController.java
  src/main/java/com/akatsuki/pioms/admin/dto/AdminDTO.java
  src/main/java/com/akatsuki/pioms/admin/entity/Admin.java
  src/main/java/com/akatsuki/pioms/admin/repository/AdminRepository.java
  src/main/java/com/akatsuki/pioms/admin/service/AdminService.java
  src/main/java/com/akatsuki/pioms/admin/service/AdminServiceImpl.java
  src/main/java/com/akatsuki/pioms/ask/repository/AdminRepository.java
  src/main/java/com/akatsuki/pioms/franchise/entity/FranchiseEntity.java
Labels: ✨ Feature

#56 New administrator registration function
  src/main/java/com/akatsuki/pioms/admin/aggregate/Admin.java
  src/main/java/com/akatsuki/pioms/admin/controller/AdminInfoController.java
  src/main/java/com/akatsuki/pioms/admin/service/AdminService.java
  src/main/java/com/akatsuki/pioms/admin/service/AdminServiceImpl.java
Labels: ✨ Feature

#57 administrator information editing function
  src/main/java/com/akatsuki/pioms/admin/controller/AdminInfoController.java
  src/main/java/com/akatsuki/pioms/admin/service/AdminInfoService.java
  src/main/java/com/akatsuki/pioms/admin/service/AdminInfoServiceImpl.java
Labels: ✨ Feature

#58 Create, Update CategoryFirst
  build.gradle
  src/main/java/com/akatsuki/pioms/ask/dto/AskDTO.java
  src/main/java/com/akatsuki/pioms/ask/entity/AskEntity.java
  src/main/java/com/akatsuki/pioms/category/controller/CategoryFirstController.java
  src/main/java/com/akatsuki/pioms/category/controller/CategoryThirdController.java
  src/main/java/com/akatsuki/pioms/category/dto/CategoryThirdDTO.java
  src/main/java/com/akatsuki/pioms/category/entity/CategoryFirst.java
  src/main/java/com/akatsuki/pioms/category/entity/CategorySecond.java
  src/main/java/com/akatsuki/pioms/category/entity/CategoryThird.java
  src/main/java/com/akatsuki/pioms/category/service/CategoryFirstService.java
  src/main/java/com/akatsuki/pioms/category/service/CategoryFirstServiceImpl.java
  src/main/java/com/akatsuki/pioms/category/service/CategoryThirdService.java
  src/main/java/com/akatsuki/pioms/category/service/CategoryThirdServiceImpl.java
  src/main/java/com/akatsuki/pioms/category/vo/RequestCategoryFirstPost.java
  src/main/java/com/akatsuki/pioms/category/vo/RequestCategoryFirstUpdate.java
  src/main/java/com/akatsuki/pioms/category/vo/RequestCategoryThirdPost.java
  src/main/java/com/akatsuki/pioms/category/vo/RequestCategoryThirdUpdate.java
  src/main/java/com/akatsuki/pioms/category/vo/ResponseCategoryFirstPost.java
  src/main/java/com/akatsuki/pioms/category/vo/ResponseCategoryFirstUpdate.java
  src/main/java/com/akatsuki/pioms/category/vo/ResponseCategoryPost.java
  src/main/java/com/akatsuki/pioms/category/vo/ResponseCategoryThirdPost.java
  src/main/java/com/akatsuki/pioms/category/vo/ResponseCategoryThirdProduct.java
  src/main/java/com/akatsuki/pioms/product/controller/ProductController.java
  src/main/java/com/akatsuki/pioms/product/entity/Product.java
  src/main/java/com/akatsuki/pioms/product/repository/ProductRepository.java
  src/main/java/com/akatsuki/pioms/product/service/ProductService.java
  src/main/java/com/akatsuki/pioms/product/service/ProductServiceImpl.java
  src/main/java/com/akatsuki/pioms/product/vo/ProductVO.java
  src/main/java/com/akatsuki/pioms/product/vo/RequestProductPost.java
  src/main/java/com/akatsuki/pioms/product/vo/ResponseProductPost.java
Labels: ✨ Feature

#65 Franchise Inquiry Implementation
  src/main/java/com/akatsuki/pioms/franchise/aggregate/DELIVERY_DATE.java
  src/main/java/com/akatsuki/pioms/franchise/aggregate/Franchise.java
  src/main/java/com/akatsuki/pioms/franchise/controller/FranchiseController.java
  src/main/java/com/akatsuki/pioms/franchise/repository/FranchiseRepository.java
  src/main/java/com/akatsuki/pioms/franchise/service/FranchiseService.java
  src/main/java/com/akatsuki/pioms/franchise/service/FranchiseServiceImpl.java
  src/main/java/com/akatsuki/pioms/frowner/aggregate/FranchiseOwner.java
  src/main/java/com/akatsuki/pioms/frwarehouse/aggregate/FranchiseWarehouse.java
  src/main/java/com/akatsuki/pioms/frwarehouse/controller/franchiseWarehouseController.java
  src/main/java/com/akatsuki/pioms/frwarehouse/repository/FranchiseWarehouseRepository.java
  src/main/java/com/akatsuki/pioms/frwarehouse/service/FranchiseWarehouseService.java
  src/main/java/com/akatsuki/pioms/frwarehouse/service/FranchiseWarehouseServiceImpl.java
  src/main/java/com/akatsuki/pioms/invoice/service/InvoiceServiceImpl.java
  src/main/java/com/akatsuki/pioms/order/service/OrderServiceImpl.java
  src/main/java/com/akatsuki/pioms/order/vo/OrderVO.java
Labels: ✨ Feature

#69 Create categoryThird log (enroll, update)
  src/main/java/com/akatsuki/pioms/ask/dto/AskDTO.java
  src/main/java/com/akatsuki/pioms/ask/etc/ADMIN_ROLE.java
  src/main/java/com/akatsuki/pioms/ask/service/AskServiceImpl.java
  src/main/java/com/akatsuki/pioms/categoryThird/service/CategoryThirdServiceImpl.java
  src/main/java/com/akatsuki/pioms/franchise/aggregate/Franchise.java
  src/main/java/com/akatsuki/pioms/frowner/repository/FranchiseOwnerRepository.java
  src/main/java/com/akatsuki/pioms/log/aggregate/Log.java
  src/main/java/com/akatsuki/pioms/log/controller/LogController.java
  src/main/java/com/akatsuki/pioms/log/etc/LogStatus.java
  src/main/java/com/akatsuki/pioms/log/repository/LogRepository.java
  src/main/java/com/akatsuki/pioms/log/service/LogService.java
  src/main/java/com/akatsuki/pioms/log/service/LogServiceImpl.java
Labels: ✨ Feature

#73 Refactoring Order, Add docs in OrderService, Add Swagger in Order, Add logic when check order's product not equal count
  src/main/java/com/akatsuki/pioms/order/controller/AdminOrderController.java
  src/main/java/com/akatsuki/pioms/order/dto/OrderDTO.java
  src/main/java/com/akatsuki/pioms/order/entity/OrderProduct.java
  src/main/java/com/akatsuki/pioms/order/repository/OrderProductRepository.java
  src/main/java/com/akatsuki/pioms/order/repository/OrderRepository.java
  src/main/java/com/akatsuki/pioms/order/service/OrderService.java
  src/main/java/com/akatsuki/pioms/order/service/OrderServiceImpl.java
  src/main/java/com/akatsuki/pioms/product/service/ProductService.java
  src/main/java/com/akatsuki/pioms/product/service/ProductServiceImpl.java
Labels: 📃 Docs, ✨ Feature

#75 Update CategorySecond for Log
  src/main/java/com/akatsuki/pioms/categorySecond/aggregate/CategorySecond.java
  src/main/java/com/akatsuki/pioms/categorySecond/aggregate/RequestCategorySecondPost.java
  src/main/java/com/akatsuki/pioms/categorySecond/aggregate/RequestCategorySecondUpdate.java
  src/main/java/com/akatsuki/pioms/categorySecond/aggregate/ResponseCategorySecondPost.java
  src/main/java/com/akatsuki/pioms/categorySecond/aggregate/ResponseCategorySecondUpdate.java
  src/main/java/com/akatsuki/pioms/categorySecond/service/CategorySecondServiceImpl.java
  src/main/java/com/akatsuki/pioms/categoryThird/service/CategoryThirdServiceImpl.java
Labels: ✨ Feature, 🔨 Refactor

#70 Code refactoring And Update,Create Product (auto-date)
  src/main/java/com/akatsuki/pioms/categoryThird/aggregate/CategoryThird.java
  src/main/java/com/akatsuki/pioms/categoryThird/aggregate/RequestCategoryThirdUpdate.java
  src/main/java/com/akatsuki/pioms/categoryThird/service/CategoryThirdServiceImpl.java
  src/main/java/com/akatsuki/pioms/product/aggregate/Product.java
  src/main/java/com/akatsuki/pioms/product/aggregate/RequestProduct.java
  src/main/java/com/akatsuki/pioms/product/aggregate/ResponseProduct.java
  src/main/java/com/akatsuki/pioms/product/aggregate/ResponseProducts.java
  src/main/java/com/akatsuki/pioms/product/service/ProductServiceImpl.java
Labels: ✨ Feature

#76 Edit franchise information and delete franchise
  src/main/java/com/akatsuki/pioms/admin/aggregate/Admin.java
  src/main/java/com/akatsuki/pioms/franchise/aggregate/Franchise.java
  src/main/java/com/akatsuki/pioms/franchise/controller/AdminOnlyFranchiseController.java
  src/main/java/com/akatsuki/pioms/franchise/controller/FranchiseOnlyFranchiseController.java
  src/main/java/com/akatsuki/pioms/franchise/service/FranchiseService.java
  src/main/java/com/akatsuki/pioms/franchise/service/FranchiseServiceImpl.java
Labels: ✨ Feature

#78 Update CategoryFirst for Log
  src/main/java/com/akatsuki/pioms/categoryFirst/service/CategoryFirstServiceImpl.java
Labels: ✨ Feature, 🔨 Refactor

#81 Update FranchiseWarehouse
  src/main/java/com/akatsuki/pioms/frwarehouse/aggregate/RequestFranchiseWarehouseUpdate.java
  src/main/java/com/akatsuki/pioms/frwarehouse/aggregate/ResponseFranchiseWarehouseUpdate.java
  src/main/java/com/akatsuki/pioms/frwarehouse/controller/franchiseWarehouseController.java
  src/main/java/com/akatsuki/pioms/frwarehouse/service/FranchiseWarehouseService.java
  src/main/java/com/akatsuki/pioms/frwarehouse/service/FranchiseWarehouseServiceImpl.java
Labels: ✨ Feature

#83 Add Code for Create,Update,Delete product Log
  src/main/java/com/akatsuki/pioms/product/service/ProductServiceImpl.java
Labels: ✨ Feature, 🔨 Refactor

#85 Delete CategoryThird without products by code
  src/main/java/com/akatsuki/pioms/categorySecond/aggregate/CategorySecondListVO.java
  src/main/java/com/akatsuki/pioms/categorySecond/aggregate/CategorySecondVO.java
  src/main/java/com/akatsuki/pioms/categoryThird/controller/CategoryThirdController.java
  src/main/java/com/akatsuki/pioms/categoryThird/repository/CategoryThirdRepository.java
  src/main/java/com/akatsuki/pioms/categoryThird/service/CategoryThirdService.java
  src/main/java/com/akatsuki/pioms/categoryThird/service/CategoryThirdServiceImpl.java
  src/main/java/com/akatsuki/pioms/product/repository/ProductRepository.java
Labels: ✨ Feature

#94 feat: #89 Refactoring Company for Add Update Log
  src/main/java/com/akatsuki/pioms/company/service/CompanyServiceImpl.java
Labels: ✨ Feature, 🔨 Refactor

#95 Delivery Driver Info CRUD
  src/main/java/com/akatsuki/pioms/driver/aggregate/DeliveryDriver.java
  src/main/java/com/akatsuki/pioms/driver/controller/AdminOnlyDriverInfoController.java
  src/main/java/com/akatsuki/pioms/driver/controller/DriverOnlyDriverInfoController.java
  src/main/java/com/akatsuki/pioms/driver/repository/DeliveryDriverRepository.java
  src/main/java/com/akatsuki/pioms/driver/service/DeliveryDriverService.java
  src/main/java/com/akatsuki/pioms/driver/service/DeliveryDriverServiceImpl.java
Labels: ✨ Feature

#97 feat: #96 Refactoring Admin for Add Create,Update,Delete Log
  src/main/java/com/akatsuki/pioms/admin/service/AdminInfoServiceImpl.java
Labels: ✨ Feature, 🔨 Refactor

#102 fix error of merging
  src/main/java/com/akatsuki/pioms/frwarehouse/service/FranchiseWarehouseService.java
  src/test/java/com/akatsuki/pioms/invoice/service/InvoiceServiceTest.java
Labels: 🐞 BugFix

#104 View Notice full and details for Admin and Franchise
  src/main/java/com/akatsuki/pioms/notice/aggregate/Notice.java
  src/main/java/com/akatsuki/pioms/notice/aggregate/NoticeVO.java
  src/main/java/com/akatsuki/pioms/notice/controller/NoticeAdminController.java
  src/main/java/com/akatsuki/pioms/notice/controller/NoticeFranchiseController.java
  src/main/java/com/akatsuki/pioms/notice/repository/NoticeRepository.java
  src/main/java/com/akatsuki/pioms/notice/service/NoticeService.java
  src/main/java/com/akatsuki/pioms/notice/service/NoticeServiceImpl.java
Labels: ✨ Feature

#118 Franchise Owner info CRUD complete
  src/main/java/com/akatsuki/pioms/franchise/aggregate/Franchise.java
  src/main/java/com/akatsuki/pioms/frowner/aggregate/FranchiseOwner.java
  src/main/java/com/akatsuki/pioms/frowner/controller/AdminOnlyFrOwnerController.java
  src/main/java/com/akatsuki/pioms/frowner/controller/FrOwnerOnlyFrOwnerController.java
  src/main/java/com/akatsuki/pioms/frowner/dto/FranchiseOwnerDTO.java
  src/main/java/com/akatsuki/pioms/frowner/repository/FranchiseOwnerRepository.java
  src/main/java/com/akatsuki/pioms/frowner/service/FranchiseOwnerService.java
  src/main/java/com/akatsuki/pioms/frowner/service/FranchiseOwnerServiceImpl.java
Labels: ✨ Feature

#119 code refactoring and delete Optional Function
  src/main/java/com/akatsuki/pioms/categoryFirst/controller/CategoryFirstController.java
  src/main/java/com/akatsuki/pioms/categoryFirst/service/CategoryFirstService.java
  src/main/java/com/akatsuki/pioms/categoryFirst/service/CategoryFirstServiceImpl.java
  src/main/java/com/akatsuki/pioms/categorySecond/aggregate/CategorySecond.java
  src/main/java/com/akatsuki/pioms/categorySecond/controller/CategorySecondController.java
  src/main/java/com/akatsuki/pioms/categorySecond/repository/CategorySecondRepository.java
  src/main/java/com/akatsuki/pioms/categorySecond/service/CategorySecondService.java
  src/main/java/com/akatsuki/pioms/categorySecond/service/CategorySecondServiceImpl.java
  src/main/java/com/akatsuki/pioms/categoryThird/aggregate/CategoryThird.java
  src/main/java/com/akatsuki/pioms/categoryThird/controller/CategoryThirdController.java
  src/main/java/com/akatsuki/pioms/categoryThird/service/CategoryThirdService.java
  src/main/java/com/akatsuki/pioms/categoryThird/service/CategoryThirdServiceImpl.java
  src/main/java/com/akatsuki/pioms/frwarehouse/controller/franchiseWarehouseController.java
  src/main/java/com/akatsuki/pioms/frwarehouse/service/FranchiseWarehouseService.java
  src/main/java/com/akatsuki/pioms/frwarehouse/service/FranchiseWarehouseServiceImpl.java
  src/main/java/com/akatsuki/pioms/product/aggregate/Product.java
  src/main/java/com/akatsuki/pioms/product/controller/ProductController.java
  src/main/java/com/akatsuki/pioms/product/repository/ProductRepository.java
  src/main/java/com/akatsuki/pioms/product/service/ProductService.java
  src/main/java/com/akatsuki/pioms/product/service/ProductServiceImpl.java
Labels: ✨ Feature, 🔨 Refactor

#122 Refactoring services, add test of exchange
  src/main/java/com/akatsuki/pioms/admin/aggregate/Admin.java
  src/main/java/com/akatsuki/pioms/admin/dto/AdminDTO.java
  src/main/java/com/akatsuki/pioms/exchange/aggregate/Exchange.java
  src/main/java/com/akatsuki/pioms/exchange/aggregate/ExchangeProduct.java
  src/main/java/com/akatsuki/pioms/exchange/aggregate/ExchangeProductVO.java
  src/main/java/com/akatsuki/pioms/exchange/aggregate/ResponseExchange.java
  src/main/java/com/akatsuki/pioms/exchange/controller/ExchangeController.java
  src/main/java/com/akatsuki/pioms/exchange/dto/ExchangeDTO.java
  src/main/java/com/akatsuki/pioms/exchange/dto/ExchangeProductDTO.java
  src/main/java/com/akatsuki/pioms/exchange/repository/ExchangeProductRepository.java
  src/main/java/com/akatsuki/pioms/exchange/repository/ExchangeRepository.java
  src/main/java/com/akatsuki/pioms/exchange/service/ExchangeService.java
  src/main/java/com/akatsuki/pioms/exchange/service/ExchangeServiceImpl.java
  src/main/java/com/akatsuki/pioms/franchise/aggregate/Franchise.java
  src/main/java/com/akatsuki/pioms/franchise/dto/FranchiseDTO.java
  src/main/java/com/akatsuki/pioms/franchise/repository/FranchiseRepository.java
  src/main/java/com/akatsuki/pioms/frowner/aggregate/FranchiseOwner.java
  src/main/java/com/akatsuki/pioms/frowner/dto/FranchiseOwnerDTO.java
  src/main/java/com/akatsuki/pioms/frwarehouse/service/FranchiseWarehouseService.java
  src/main/java/com/akatsuki/pioms/frwarehouse/service/FranchiseWarehouseServiceImpl.java
  src/main/java/com/akatsuki/pioms/invoice/aggregate/InvoiceEntity.java
  src/main/java/com/akatsuki/pioms/invoice/aggregate/ResponseInvoice.java
  src/main/java/com/akatsuki/pioms/invoice/aggregate/ResponseInvoiceList.java
  src/main/java/com/akatsuki/pioms/invoice/controller/InvoiceController.java
  src/main/java/com/akatsuki/pioms/invoice/dto/InvoiceDTO.java
  src/main/java/com/akatsuki/pioms/invoice/service/InvoiceService.java
  src/main/java/com/akatsuki/pioms/invoice/service/InvoiceServiceImpl.java
  src/main/java/com/akatsuki/pioms/order/aggregate/Order.java
  src/main/java/com/akatsuki/pioms/order/aggregate/OrderListVO.java
  src/main/java/com/akatsuki/pioms/order/aggregate/OrderProduct.java
  src/main/java/com/akatsuki/pioms/order/aggregate/OrderVO.java
  src/main/java/com/akatsuki/pioms/order/controller/AdminOrderController.java
  src/main/java/com/akatsuki/pioms/order/controller/FranchiseOrderController.java
  src/main/java/com/akatsuki/pioms/order/dto/OrderDTO.java
  src/main/java/com/akatsuki/pioms/order/dto/OrderProductDTO.java
  src/main/java/com/akatsuki/pioms/order/service/OrderService.java
  src/main/java/com/akatsuki/pioms/order/service/OrderServiceImpl.java
  src/main/java/com/akatsuki/pioms/product/aggregate/Product.java
  src/main/java/com/akatsuki/pioms/product/dto/ProductDTO.java
  src/main/java/com/akatsuki/pioms/product/service/ProductServiceImpl.java
  src/main/java/com/akatsuki/pioms/specs/aggregate/ResponseSpecs.java
  src/main/java/com/akatsuki/pioms/specs/controller/SpecsController.java
  src/main/java/com/akatsuki/pioms/specs/dto/SpecsDTO.java
  src/main/java/com/akatsuki/pioms/specs/service/SpecsService.java
  src/main/java/com/akatsuki/pioms/specs/service/SpecsServiceImpl.java
  src/test/java/com/akatsuki/pioms/exchange/service/ExchangeServiceTest.java
  src/test/java/com/akatsuki/pioms/invoice/service/InvoiceServiceTest.java
Labels: 🔨 Refactor, ✅ Test

#124 feat: #123 Create Notice for Root Admin Function Implementation
  src/main/java/com/akatsuki/pioms/notice/aggregate/Notice.java
  src/main/java/com/akatsuki/pioms/notice/aggregate/NoticeVO.java
  src/main/java/com/akatsuki/pioms/notice/controller/NoticeAdminController.java
  src/main/java/com/akatsuki/pioms/notice/controller/NoticeFranchiseController.java
  src/main/java/com/akatsuki/pioms/notice/dto/NoticeDTO.java
  src/main/java/com/akatsuki/pioms/notice/repository/NoticeRepository.java
  src/main/java/com/akatsuki/pioms/notice/service/NoticeService.java
  src/main/java/com/akatsuki/pioms/notice/service/NoticeServiceImpl.java
Labels: ✨ Feature

#130 refactor: delete unused test
  build.gradle
  src/main/java/com/akatsuki/pioms/event/OrderEvent.java
  src/main/java/com/akatsuki/pioms/exchange/aggregate/Exchange.java
  src/main/java/com/akatsuki/pioms/exchange/aggregate/ResponseExchange.java
  src/main/java/com/akatsuki/pioms/exchange/dto/ExchangeDTO.java
  src/main/java/com/akatsuki/pioms/franchise/dto/FranchiseDTO.java
  src/main/java/com/akatsuki/pioms/frowner/aggregate/FranchiseOwner.java
  src/main/java/com/akatsuki/pioms/frowner/dto/FranchiseOwnerDTO.java
  src/main/java/com/akatsuki/pioms/invoice/aggregate/InvoiceEntity.java
  src/main/java/com/akatsuki/pioms/invoice/aggregate/ResponseInvoice.java
  src/main/java/com/akatsuki/pioms/invoice/aggregate/ResponseInvoiceList.java
  src/main/java/com/akatsuki/pioms/invoice/controller/InvoiceController.java
  src/main/java/com/akatsuki/pioms/invoice/dto/InvoiceDTO.java
  src/main/java/com/akatsuki/pioms/invoice/service/InvoiceService.java
  src/main/java/com/akatsuki/pioms/invoice/service/InvoiceServiceImpl.java
  src/main/java/com/akatsuki/pioms/order/aggregate/Order.java
  src/main/java/com/akatsuki/pioms/order/aggregate/OrderListVO.java
  src/main/java/com/akatsuki/pioms/order/aggregate/OrderProduct.java
  src/main/java/com/akatsuki/pioms/order/aggregate/OrderVO.java
  src/main/java/com/akatsuki/pioms/order/controller/AdminOrderController.java
  src/main/java/com/akatsuki/pioms/order/controller/FranchiseOrderController.java
  src/main/java/com/akatsuki/pioms/order/dto/OrderDTO.java
  src/main/java/com/akatsuki/pioms/order/dto/OrderProductDTO.java
  src/main/java/com/akatsuki/pioms/order/repository/OrderRepository.java
  src/main/java/com/akatsuki/pioms/order/service/OrderFacade.java
  src/main/java/com/akatsuki/pioms/order/service/OrderService.java
  src/main/java/com/akatsuki/pioms/order/service/OrderServiceImpl.java
  src/main/java/com/akatsuki/pioms/product/controller/ProductController.java
  src/main/java/com/akatsuki/pioms/product/service/ProductService.java
  src/main/java/com/akatsuki/pioms/product/service/ProductServiceImpl.java
  src/main/java/com/akatsuki/pioms/specs/aggregate/ResponseSpecs.java
  src/main/java/com/akatsuki/pioms/specs/aggregate/SpecsEntity.java
  src/main/java/com/akatsuki/pioms/specs/controller/SpecsController.java
  src/main/java/com/akatsuki/pioms/specs/dto/SpecsDTO.java
  src/main/java/com/akatsuki/pioms/specs/service/SpecsService.java
  src/main/java/com/akatsuki/pioms/specs/service/SpecsServiceImpl.java
  src/test/java/com/akatsuki/pioms/exchange/service/ExchangeServiceTest.java
  src/test/java/com/akatsuki/pioms/frwarehouse/service/FranchiseWarehouseServiceTest.java
  src/test/java/com/akatsuki/pioms/invoice/service/InvoiceServiceTest.java
  src/test/java/com/akatsuki/pioms/order/service/OrderServiceTest.java
  src/test/java/com/akatsuki/pioms/product/service/ProductServiceTest.java
  src/test/java/com/akatsuki/pioms/specs/service/SpecsServiceTest.java
Labels: 🔨 Refactor

#131 Add security settings
  src/main/java/com/akatsuki/pioms/admin/controller/AdminInfoController.java
  src/main/java/com/akatsuki/pioms/admin/service/AdminInfoService.java
  src/main/java/com/akatsuki/pioms/admin/service/AdminInfoServiceImpl.java
  src/main/java/com/akatsuki/pioms/config/SecurityConfig.java
Labels: ✨ Feature, 🔨 Refactor

#133 refactoring specs
  src/main/java/com/akatsuki/pioms/order/dto/OrderProductDTO.java
  src/main/java/com/akatsuki/pioms/specs/aggregate/ResponseSpecs.java
  src/main/java/com/akatsuki/pioms/specs/aggregate/SpecsEntity.java
  src/main/java/com/akatsuki/pioms/specs/controller/AdminSpecsController.java
  src/main/java/com/akatsuki/pioms/specs/controller/SpecsController.java
  src/main/java/com/akatsuki/pioms/specs/dto/SpecsDTO.java
  src/main/java/com/akatsuki/pioms/specs/repository/SpecsRepository.java
  src/main/java/com/akatsuki/pioms/specs/service/SpecsService.java
  src/main/java/com/akatsuki/pioms/specs/service/SpecsServiceImpl.java
Labels: 🔨 Refactor

#138 Add administrator login function
  src/main/java/com/akatsuki/pioms/admin/aggregate/AdminLoginRequest.java
  src/main/java/com/akatsuki/pioms/admin/aggregate/AdminVO.java
  src/main/java/com/akatsuki/pioms/admin/controller/AdminInfoController.java
  src/main/java/com/akatsuki/pioms/admin/repository/AdminRepository.java
  src/main/java/com/akatsuki/pioms/admin/service/AdminInfoService.java
  src/main/java/com/akatsuki/pioms/admin/service/AdminInfoServiceImpl.java
  src/main/java/com/akatsuki/pioms/config/SecurityConfig.java
  src/test/java/com/akatsuki/pioms/admin/service/AdminInfoServiceTest.java
  src/test/java/com/akatsuki/pioms/exchange/service/ExchangeServiceTest.java
Labels: ✨ Feature, 🔨 Refactor

#141 feat: #137 Update Notice for Root Admin Function Implementation
  src/main/java/com/akatsuki/pioms/notice/aggregate/NoticeVO.java
  src/main/java/com/akatsuki/pioms/notice/controller/NoticeAdminController.java
  src/main/java/com/akatsuki/pioms/notice/service/NoticeService.java
  src/main/java/com/akatsuki/pioms/notice/service/NoticeServiceImpl.java
Labels: ✨ Feature

#153 Refactoring Invoice, Order, Exchange, Add Delivery Region Entity, DTO, Test Inovice
  src/main/java/com/akatsuki/pioms/driver/DeliveryRegionDTO.java
  src/main/java/com/akatsuki/pioms/driver/aggregate/DeliveryRegion.java
  src/main/java/com/akatsuki/pioms/exchange/aggregate/EXCHANGE_STATUS.java
  src/main/java/com/akatsuki/pioms/exchange/aggregate/ExchangeProduct.java
  src/main/java/com/akatsuki/pioms/exchange/aggregate/ExchangeProductVO.java
  src/main/java/com/akatsuki/pioms/exchange/controller/AdminExchangeController.java
  src/main/java/com/akatsuki/pioms/exchange/controller/FranchiseExchangeController.java
  src/main/java/com/akatsuki/pioms/exchange/dto/ExchangeProductDTO.java
  src/main/java/com/akatsuki/pioms/exchange/repository/ExchangeRepository.java
  src/main/java/com/akatsuki/pioms/exchange/service/ExchangeService.java
  src/main/java/com/akatsuki/pioms/exchange/service/ExchangeServiceImpl.java
  src/main/java/com/akatsuki/pioms/invoice/aggregate/DELIVERY_STATUS.java
  src/main/java/com/akatsuki/pioms/invoice/aggregate/Invoice.java
  src/main/java/com/akatsuki/pioms/invoice/aggregate/ResponseInvoice.java
  src/main/java/com/akatsuki/pioms/invoice/aggregate/ResponseInvoiceList.java
  src/main/java/com/akatsuki/pioms/invoice/aggregate/ResponseInvoiceOrderProduct.java
  src/main/java/com/akatsuki/pioms/invoice/controller/InvoiceController.java
  src/main/java/com/akatsuki/pioms/invoice/dto/InvoiceDTO.java
  src/main/java/com/akatsuki/pioms/invoice/repository/InvoiceRepository.java
  src/main/java/com/akatsuki/pioms/invoice/service/InvoiceService.java
  src/main/java/com/akatsuki/pioms/invoice/service/InvoiceServiceImpl.java
  src/main/java/com/akatsuki/pioms/order/controller/AdminOrderController.java
  src/main/java/com/akatsuki/pioms/order/service/OrderFacade.java
  src/main/java/com/akatsuki/pioms/order/service/OrderService.java
  src/main/java/com/akatsuki/pioms/order/service/OrderServiceImpl.java
  src/main/java/com/akatsuki/pioms/product/service/ProductServiceImpl.java
  src/test/java/com/akatsuki/pioms/exchange/service/ExchangeServiceTest.java
  src/test/java/com/akatsuki/pioms/invoice/service/InvoiceServiceTest.java
Labels: 🔨 Refactor, ✅ Test

#156 Refactoring Franchise for History of create,update,delete franchise info
  src/main/java/com/akatsuki/pioms/franchise/service/FranchiseServiceImpl.java
Labels: 🔨 Refactor

#157 Added login function and password encryption
  src/main/java/com/akatsuki/pioms/admin/controller/AdminInfoController.java
  src/main/java/com/akatsuki/pioms/admin/service/AdminInfoService.java
  src/main/java/com/akatsuki/pioms/admin/service/AdminInfoServiceImpl.java
  src/main/java/com/akatsuki/pioms/config/SecurityConfig.java
  src/main/java/com/akatsuki/pioms/driver/dto/DeliveryRegionDTO.java
  src/main/java/com/akatsuki/pioms/driver/service/DeliveryDriverServiceImpl.java
  src/main/java/com/akatsuki/pioms/frowner/repository/FranchiseOwnerRepository.java
  src/main/java/com/akatsuki/pioms/frowner/service/FranchiseOwnerServiceImpl.java
  src/main/java/com/akatsuki/pioms/invoice/dto/InvoiceDTO.java
  src/main/java/com/akatsuki/pioms/login/aggregate/AdminLoginRequest.java
  src/main/java/com/akatsuki/pioms/login/aggregate/DeliveryDriverLoginRequest.java
  src/main/java/com/akatsuki/pioms/login/aggregate/FranchiseOwnerLoginRequest.java
  src/main/java/com/akatsuki/pioms/login/controller/LoginController.java
  src/main/java/com/akatsuki/pioms/login/service/LoginService.java
  src/main/java/com/akatsuki/pioms/login/service/LoginServiceImpl.java
  src/test/java/com/akatsuki/pioms/admin/service/AdminInfoServiceTest.java
Labels: ✨ Feature, 🔨 Refactor

#160 Refactoring FranchiseOwner for History of create,update,delete franchiseOwner info
  src/main/java/com/akatsuki/pioms/frowner/service/FranchiseOwnerServiceImpl.java
Labels: 🔨 Refactor

#164 Create order, invoice test. refactoring code
  src/main/java/com/akatsuki/pioms/driver/dto/DeliveryRegionDTO.java
  src/main/java/com/akatsuki/pioms/driver/repository/DeliveryRegionRepository.java
  src/main/java/com/akatsuki/pioms/driver/service/DeliveryService.java
  src/main/java/com/akatsuki/pioms/driver/service/DeliveryServiceImpl.java
  src/main/java/com/akatsuki/pioms/franchise/aggregate/Franchise.java
  src/main/java/com/akatsuki/pioms/invoice/aggregate/Invoice.java
  src/main/java/com/akatsuki/pioms/invoice/aggregate/ResponseInvoice.java
  src/main/java/com/akatsuki/pioms/invoice/dto/InvoiceDTO.java
  src/main/java/com/akatsuki/pioms/invoice/repository/InvoiceRepository.java
  src/main/java/com/akatsuki/pioms/invoice/service/InvoiceService.java
  src/main/java/com/akatsuki/pioms/invoice/service/InvoiceServiceImpl.java
  src/main/java/com/akatsuki/pioms/order/aggregate/Order.java
  src/main/java/com/akatsuki/pioms/order/controller/FranchiseOrderController.java
  src/main/java/com/akatsuki/pioms/order/dto/OrderDTO.java
  src/main/java/com/akatsuki/pioms/order/service/OrderFacade.java
  src/main/java/com/akatsuki/pioms/order/service/OrderService.java
  src/main/java/com/akatsuki/pioms/order/service/OrderServiceImpl.java
  src/test/java/com/akatsuki/pioms/invoice/service/InvoiceServiceTest.java
  src/test/java/com/akatsuki/pioms/order/service/OrderFacadeTest.java
Labels: 🔨 Refactor, ✅ Test

#165 Admin auth check and code refactoring
  src/main/java/com/akatsuki/pioms/categoryFirst/controller/CategoryFirstController.java
  src/main/java/com/akatsuki/pioms/categoryFirst/service/CategoryFirstService.java
  src/main/java/com/akatsuki/pioms/categoryFirst/service/CategoryFirstServiceImpl.java
  src/main/java/com/akatsuki/pioms/categorySecond/controller/CategorySecondController.java
  src/main/java/com/akatsuki/pioms/categorySecond/service/CategorySecondService.java
  src/main/java/com/akatsuki/pioms/categorySecond/service/CategorySecondServiceImpl.java
  src/main/java/com/akatsuki/pioms/categoryThird/controller/CategoryThirdController.java
  src/main/java/com/akatsuki/pioms/categoryThird/service/CategoryThirdService.java
  src/main/java/com/akatsuki/pioms/categoryThird/service/CategoryThirdServiceImpl.java
  src/main/java/com/akatsuki/pioms/frwarehouse/controller/franchiseWarehouseController.java
  src/main/java/com/akatsuki/pioms/frwarehouse/service/FranchiseWarehouseService.java
  src/main/java/com/akatsuki/pioms/frwarehouse/service/FranchiseWarehouseServiceImpl.java
  src/main/java/com/akatsuki/pioms/product/controller/ProductController.java
  src/main/java/com/akatsuki/pioms/product/service/ProductService.java
  src/main/java/com/akatsuki/pioms/product/service/ProductServiceImpl.java
  src/test/java/com/akatsuki/pioms/categoryFirst/service/CategoryFirstServiceTest.java
  src/test/java/com/akatsuki/pioms/categorySecond/service/CategorySecondServiceTest.java
  src/test/java/com/akatsuki/pioms/categoryThird/service/CategoryThirdServiceTest.java
  src/test/java/com/akatsuki/pioms/frwarehouse/service/FranchiseWarehouseServiceTest.java
  src/test/java/com/akatsuki/pioms/product/service/ProductServiceTest.java
Labels: ✨ Feature, 🔨 Refactor, ✅ Test

#167 feat: #139 Delete Notice for Root Admin Fuction Implementation
  src/main/java/com/akatsuki/pioms/notice/controller/NoticeAdminController.java
  src/main/java/com/akatsuki/pioms/notice/service/NoticeService.java
  src/main/java/com/akatsuki/pioms/notice/service/NoticeServiceImpl.java
  src/test/java/com/akatsuki/pioms/notice/service/NoticeServiceTest.java
Labels: ✨ Feature

#169 test: #168 Test for Notice (read - All, Details)
  src/test/java/com/akatsuki/pioms/notice/service/NoticeServiceTest.java
Labels: ✅ Test

#173 Create TestCode of Ask
  src/main/java/com/akatsuki/pioms/ask/dto/AskListDTO.java
  src/main/java/com/akatsuki/pioms/ask/repository/AskRepository.java
  src/main/java/com/akatsuki/pioms/ask/service/AskServiceImpl.java
  src/test/java/com/akatsuki/pioms/ask/service/AskServiceTests.java
Labels: 🔨 Refactor, ✅ Test

#175 Category , product log code refactoring
  src/main/java/com/akatsuki/pioms/categoryFirst/service/CategoryFirstServiceImpl.java
  src/main/java/com/akatsuki/pioms/categorySecond/service/CategorySecondServiceImpl.java
  src/main/java/com/akatsuki/pioms/categoryThird/service/CategoryThirdServiceImpl.java
  src/main/java/com/akatsuki/pioms/product/service/ProductServiceImpl.java
Labels: 🔨 Refactor

#180 Code refactoring and adminService test code modification
  build.gradle
  src/main/java/com/akatsuki/pioms/admin/aggregate/Admin.java
  src/main/java/com/akatsuki/pioms/admin/controller/AdminInfoController.java
  src/main/java/com/akatsuki/pioms/admin/dto/AdminDTO.java
  src/main/java/com/akatsuki/pioms/admin/service/AdminInfoService.java
  src/main/java/com/akatsuki/pioms/admin/service/AdminInfoServiceImpl.java
  src/main/java/com/akatsuki/pioms/frowner/controller/AdminOnlyFrOwnerController.java
  src/main/java/com/akatsuki/pioms/frowner/dto/FranchiseOwnerDTO.java
  src/main/java/com/akatsuki/pioms/frowner/service/FranchiseOwnerService.java
  src/main/java/com/akatsuki/pioms/frowner/service/FranchiseOwnerServiceImpl.java
  src/test/java/com/akatsuki/pioms/admin/service/AdminInfoServiceTest.java
  src/test/java/com/akatsuki/pioms/ask/service/AskServiceTests.java
Labels: 🔨 Refactor, ✅ Test

#182 Order, Invoice, Exchange, Specs refactoring. Add Docs
  src/main/java/com/akatsuki/pioms/exchange/service/ExchangeService.java
  src/main/java/com/akatsuki/pioms/exchange/service/ExchangeServiceImpl.java
  src/main/java/com/akatsuki/pioms/frwarehouse/service/FranchiseWarehouseServiceImpl.java
  src/main/java/com/akatsuki/pioms/invoice/controller/FranchiseInvoiceController.java
  src/main/java/com/akatsuki/pioms/invoice/service/InvoiceService.java
  src/main/java/com/akatsuki/pioms/invoice/service/InvoiceServiceImpl.java
  src/main/java/com/akatsuki/pioms/order/controller/AdminOrderController.java
  src/main/java/com/akatsuki/pioms/order/repository/OrderRepository.java
  src/main/java/com/akatsuki/pioms/order/service/OrderFacade.java
  src/main/java/com/akatsuki/pioms/order/service/OrderService.java
  src/main/java/com/akatsuki/pioms/order/service/OrderServiceImpl.java
  src/main/java/com/akatsuki/pioms/specs/aggregate/Specs.java
  src/main/java/com/akatsuki/pioms/specs/controller/AdminSpecsController.java
  src/main/java/com/akatsuki/pioms/specs/controller/FranchiseSpecsController.java
  src/main/java/com/akatsuki/pioms/specs/dto/SpecsDTO.java
  src/main/java/com/akatsuki/pioms/specs/repository/SpecsRepository.java
  src/main/java/com/akatsuki/pioms/specs/service/SpecsService.java
  src/main/java/com/akatsuki/pioms/specs/service/SpecsServiceImpl.java
  src/test/java/com/akatsuki/pioms/exchange/service/ExchangeServiceTest.java
  src/test/java/com/akatsuki/pioms/invoice/service/InvoiceServiceTest.java
  src/test/java/com/akatsuki/pioms/order/service/OrderFacadeTest.java
  src/test/java/com/akatsuki/pioms/specs/service/SpecsServiceTest.java
Labels: 📃 Docs, 🐞 BugFix, 🔨 Refactor, ✅ Test

#184 Create TestCode of Log
  src/test/java/com/akatsuki/pioms/log/service/LogServiceImplTest.java
Labels: ✅ Test

#187 feat: #185 View Delivery Status 'Before_delivery' for Driver Function Implementation
  src/main/java/com/akatsuki/pioms/driver/service/DeliveryService.java
  src/main/java/com/akatsuki/pioms/driver/service/DeliveryServiceImpl.java
  src/main/java/com/akatsuki/pioms/invoice/aggregate/ResponseDriverInvoice.java
  src/main/java/com/akatsuki/pioms/invoice/controller/DriverInvoiceController.java
  src/main/java/com/akatsuki/pioms/invoice/repository/InvoiceRepository.java
  src/main/java/com/akatsuki/pioms/invoice/service/InvoiceService.java
  src/main/java/com/akatsuki/pioms/invoice/service/InvoiceServiceImpl.java
Labels: ✨ Feature

#189 Integrated test for order flow
  src/main/java/com/akatsuki/pioms/exchange/dto/ExchangeDTO.java
  src/main/java/com/akatsuki/pioms/exchange/service/ExchangeServiceImpl.java
  src/main/java/com/akatsuki/pioms/frwarehouse/controller/franchiseWarehouseController.java
  src/main/java/com/akatsuki/pioms/frwarehouse/repository/FranchiseWarehouseRepository.java
  src/main/java/com/akatsuki/pioms/frwarehouse/service/FranchiseWarehouseDTO.java
  src/main/java/com/akatsuki/pioms/frwarehouse/service/FranchiseWarehouseService.java
  src/main/java/com/akatsuki/pioms/frwarehouse/service/FranchiseWarehouseServiceImpl.java
  src/main/java/com/akatsuki/pioms/invoice/service/InvoiceServiceImpl.java
  src/main/java/com/akatsuki/pioms/order/aggregate/Order.java
  src/main/java/com/akatsuki/pioms/order/aggregate/OrderProduct.java
  src/main/java/com/akatsuki/pioms/order/aggregate/RequestPutOrder.java
  src/main/java/com/akatsuki/pioms/order/aggregate/RequestPutOrderCheck.java
  src/main/java/com/akatsuki/pioms/order/controller/FranchiseOrderController.java
  src/main/java/com/akatsuki/pioms/order/dto/OrderDTO.java
  src/main/java/com/akatsuki/pioms/order/service/OrderFacade.java
  src/main/java/com/akatsuki/pioms/order/service/OrderServiceImpl.java
  src/main/java/com/akatsuki/pioms/product/dto/ProductDTO.java
  src/main/java/com/akatsuki/pioms/product/service/ProductService.java
  src/main/java/com/akatsuki/pioms/product/service/ProductServiceImpl.java
  src/test/java/com/akatsuki/pioms/ordertest.java
Labels: ✨ Feature, 🔨 Refactor, ✅ Test

#188 Excel download feature and code refactoring
  build.gradle
  src/main/java/com/akatsuki/pioms/categoryFirst/controller/CategoryFirstController.java
  src/main/java/com/akatsuki/pioms/categoryFirst/dto/CategoryFirstDTO.java
  src/main/java/com/akatsuki/pioms/categoryFirst/service/CategoryFirstService.java
  src/main/java/com/akatsuki/pioms/categoryFirst/service/CategoryFirstServiceImpl.java
  src/main/java/com/akatsuki/pioms/categorySecond/controller/CategorySecondController.java
  src/main/java/com/akatsuki/pioms/categorySecond/dto/CategorySecondDTO.java
  src/main/java/com/akatsuki/pioms/categorySecond/service/CategorySecondService.java
  src/main/java/com/akatsuki/pioms/categorySecond/service/CategorySecondServiceImpl.java
  src/main/java/com/akatsuki/pioms/categoryThird/aggregate/CategoryThird.java
  src/main/java/com/akatsuki/pioms/categoryThird/controller/CategoryThirdController.java
  src/main/java/com/akatsuki/pioms/categoryThird/dto/CategoryThirdDTO.java
  src/main/java/com/akatsuki/pioms/categoryThird/service/CategoryThirdService.java
  src/main/java/com/akatsuki/pioms/categoryThird/service/CategoryThirdServiceImpl.java
  src/main/java/com/akatsuki/pioms/config/GlobalExceptionHandler.java
  src/main/java/com/akatsuki/pioms/excel/ProductExcelController.java
  src/main/java/com/akatsuki/pioms/product/aggregate/Product.java
  src/main/java/com/akatsuki/pioms/product/aggregate/ResponseProduct.java
  src/main/java/com/akatsuki/pioms/product/controller/ProductController.java
  src/main/java/com/akatsuki/pioms/product/dto/ProductDTO.java
  src/main/java/com/akatsuki/pioms/product/repository/ProductRepository.java
  src/main/java/com/akatsuki/pioms/product/service/ProductService.java
  src/main/java/com/akatsuki/pioms/product/service/ProductServiceImpl.java
  src/main/resources/templates/home.html
  src/test/java/com/akatsuki/pioms/categoryFirst/service/CategoryFirstServiceTest.java
  src/test/java/com/akatsuki/pioms/categoryThird/service/CategoryThirdServiceTest.java
  src/test/java/com/akatsuki/pioms/product/service/ProductServiceTest.java
Labels: 📃 Docs, ✨ Feature, 🔨 Refactor, 📬 API

#196 View Category in UpperCategory, code refactoring product + test
  src/main/java/com/akatsuki/pioms/categoryFirst/aggregate/CategoryFirst.java
  src/main/java/com/akatsuki/pioms/categoryFirst/aggregate/RequestCategoryFirst.java
  src/main/java/com/akatsuki/pioms/categoryFirst/controller/CategoryFirstController.java
  src/main/java/com/akatsuki/pioms/categoryFirst/service/CategoryFirstService.java
  src/main/java/com/akatsuki/pioms/categoryFirst/service/CategoryFirstServiceImpl.java
  src/main/java/com/akatsuki/pioms/categorySecond/aggregate/CategorySecond.java
  src/main/java/com/akatsuki/pioms/categorySecond/aggregate/RequestCategorySecond.java
  src/main/java/com/akatsuki/pioms/categorySecond/aggregate/ResponseCategorySecond.java
  src/main/java/com/akatsuki/pioms/categorySecond/controller/CategorySecondController.java
  src/main/java/com/akatsuki/pioms/categorySecond/dto/CategorySecondDTO.java
  src/main/java/com/akatsuki/pioms/categorySecond/repository/CategorySecondRepository.java
  src/main/java/com/akatsuki/pioms/categorySecond/service/CategorySecondService.java
  src/main/java/com/akatsuki/pioms/categorySecond/service/CategorySecondServiceImpl.java
  src/main/java/com/akatsuki/pioms/categoryThird/aggregate/CategoryThird.java
  src/main/java/com/akatsuki/pioms/categoryThird/aggregate/RequestCategoryThird.java
  src/main/java/com/akatsuki/pioms/categoryThird/aggregate/ResponseCategoryThird.java
  src/main/java/com/akatsuki/pioms/categoryThird/controller/CategoryThirdController.java
  src/main/java/com/akatsuki/pioms/categoryThird/dto/CategoryThirdDTO.java
  src/main/java/com/akatsuki/pioms/categoryThird/repository/CategoryThirdRepository.java
  src/main/java/com/akatsuki/pioms/categoryThird/service/CategoryThirdService.java
  src/main/java/com/akatsuki/pioms/categoryThird/service/CategoryThirdServiceImpl.java
  src/main/java/com/akatsuki/pioms/excel/ProductExcelController.java
  src/main/java/com/akatsuki/pioms/product/aggregate/ResponseProduct.java
  src/main/java/com/akatsuki/pioms/product/controller/AdminProductController.java
  src/main/java/com/akatsuki/pioms/product/controller/FrProductController.java
  src/main/java/com/akatsuki/pioms/product/dto/ProductDTO.java
  src/main/java/com/akatsuki/pioms/product/repository/ProductRepository.java
  src/main/java/com/akatsuki/pioms/product/service/ProductService.java
  src/main/java/com/akatsuki/pioms/product/service/ProductServiceImpl.java
  src/test/java/com/akatsuki/pioms/categoryFirst/service/CategoryFirstServiceTest.java
  src/test/java/com/akatsuki/pioms/categorySecond/service/CategorySecondServiceTest.java
  src/test/java/com/akatsuki/pioms/categoryThird/service/CategoryThirdServiceTest.java
  src/test/java/com/akatsuki/pioms/product/service/ProductServiceTest.java
Labels: ✨ Feature, 🔨 Refactor, ✅ Test

#199 Hot Fix : change database structure
  src/main/java/com/akatsuki/pioms/admin/service/AdminInfoServiceImpl.java
  src/main/java/com/akatsuki/pioms/config/Pagination.java
  src/main/java/com/akatsuki/pioms/driver/aggregate/DeliveryRegion.java
  src/main/java/com/akatsuki/pioms/driver/controller/DriverOnlyDriverInfoController.java
  src/main/java/com/akatsuki/pioms/driver/dto/DeliveryRegionDTO.java
  src/main/java/com/akatsuki/pioms/driver/repository/DeliveryRegionRepository.java
  src/main/java/com/akatsuki/pioms/driver/service/DeliveryService.java
  src/main/java/com/akatsuki/pioms/driver/service/DeliveryServiceImpl.java
  src/main/java/com/akatsuki/pioms/franchise/aggregate/Franchise.java
  src/main/java/com/akatsuki/pioms/franchise/dto/FranchiseDTO.java
  src/main/java/com/akatsuki/pioms/franchise/repository/FranchiseRepository.java
  src/main/java/com/akatsuki/pioms/franchise/service/FranchiseService.java
  src/main/java/com/akatsuki/pioms/franchise/service/FranchiseServiceImpl.java
  src/main/java/com/akatsuki/pioms/frwarehouse/service/FranchiseWarehouseService.java
  src/main/java/com/akatsuki/pioms/frwarehouse/service/FranchiseWarehouseServiceImpl.java
  src/main/java/com/akatsuki/pioms/invoice/aggregate/Invoice.java
  src/main/java/com/akatsuki/pioms/invoice/dto/InvoiceDTO.java
  src/main/java/com/akatsuki/pioms/invoice/repository/InvoiceRepository.java
  src/main/java/com/akatsuki/pioms/invoice/service/InvoiceServiceImpl.java
  src/main/java/com/akatsuki/pioms/order/aggregate/Order.java
  src/main/java/com/akatsuki/pioms/order/aggregate/OrderVO.java
  src/main/java/com/akatsuki/pioms/order/controller/AdminOrderController.java
  src/main/java/com/akatsuki/pioms/order/controller/FranchiseOrderController.java
  src/main/java/com/akatsuki/pioms/order/dto/OrderDTO.java
  src/main/java/com/akatsuki/pioms/order/etc/ORDER_CONDITION.java
  src/main/java/com/akatsuki/pioms/order/service/AdminOrderFacade.java
  src/main/java/com/akatsuki/pioms/order/service/FranchiseOrderFacade.java
  src/main/java/com/akatsuki/pioms/order/service/OrderService.java
  src/main/java/com/akatsuki/pioms/order/service/OrderServiceImpl.java
  src/test/java/com/akatsuki/pioms/invoice/service/InvoiceServiceTest.java
  src/test/java/com/akatsuki/pioms/order/service/OrderFacadeTest.java
  src/test/java/com/akatsuki/pioms/ordertest.java
  src/test/java/com/akatsuki/pioms/specs/service/SpecsServiceTest.java
Labels: 🐞 BugFix, 🔨 Refactor, ✅ Test

#197 Create Favorite feature
  src/main/java/com/akatsuki/pioms/frwarehouse/controller/franchiseWarehouseController.java
  src/main/java/com/akatsuki/pioms/frwarehouse/repository/FranchiseWarehouseRepository.java
  src/main/java/com/akatsuki/pioms/frwarehouse/service/FranchiseWarehouseService.java
  src/main/java/com/akatsuki/pioms/frwarehouse/service/FranchiseWarehouseServiceImpl.java
  src/test/java/com/akatsuki/pioms/frwarehouse/service/FranchiseWarehouseServiceTest.java
Labels: ✨ Feature, 🔨 Refactor

#203 Test code for product, category, frWarehouse
  build.gradle
  src/main/java/com/akatsuki/pioms/categoryFirst/controller/CategoryFirstController.java
  src/main/java/com/akatsuki/pioms/categorySecond/controller/CategorySecondController.java
  src/main/java/com/akatsuki/pioms/categoryThird/controller/CategoryThirdController.java
  src/main/java/com/akatsuki/pioms/excel/ProductExcelController.java
  src/main/java/com/akatsuki/pioms/frwarehouse/aggregate/RequestFranchiseWarehouse.java
  src/main/java/com/akatsuki/pioms/frwarehouse/aggregate/RequestFranchiseWarehouseUpdate.java
  src/main/java/com/akatsuki/pioms/frwarehouse/aggregate/ResponseFranchiseWarehouse.java
  src/main/java/com/akatsuki/pioms/frwarehouse/aggregate/ResponseFranchiseWarehouseUpdate.java
  src/main/java/com/akatsuki/pioms/frwarehouse/controller/franchiseWarehouseController.java
  src/main/java/com/akatsuki/pioms/frwarehouse/dto/FranchiseWarehouseDTO.java
  src/main/java/com/akatsuki/pioms/frwarehouse/repository/FranchiseWarehouseRepository.java
  src/main/java/com/akatsuki/pioms/frwarehouse/service/FranchiseWarehouseService.java
  src/main/java/com/akatsuki/pioms/frwarehouse/service/FranchiseWarehouseServiceImpl.java
  src/main/java/com/akatsuki/pioms/product/aggregate/RequestProduct.java
  src/main/java/com/akatsuki/pioms/product/aggregate/ResponseProduct.java
  src/main/java/com/akatsuki/pioms/product/controller/AdminProductController.java
  src/main/java/com/akatsuki/pioms/product/controller/FrProductController.java
  src/main/java/com/akatsuki/pioms/product/dto/ProductDTO.java
  src/test/java/com/akatsuki/pioms/categoryThird/service/CategoryThirdServiceTest.java
  src/test/java/com/akatsuki/pioms/frwarehouse/service/FranchiseWarehouseServiceTest.java
  src/test/java/com/akatsuki/pioms/ordertest.java
  src/test/java/com/akatsuki/pioms/product/service/ProductServiceTest.java
Labels: 🔨 Refactor, ✅ Test

#202 feat: #200 #201 View Delivery Status 'Ing_delivery', 'Complete_delivery' for Driver Function Implementation
  src/main/java/com/akatsuki/pioms/invoice/controller/DriverInvoiceController.java
  src/main/java/com/akatsuki/pioms/invoice/service/InvoiceService.java
  src/main/java/com/akatsuki/pioms/invoice/service/InvoiceServiceImpl.java
Labels: ✨ Feature

#206 Excel Download feature complete
  src/main/java/com/akatsuki/pioms/excel/ProductExcelAdminController.java
  src/main/java/com/akatsuki/pioms/excel/ProductExcelFranchiseController.java
Labels: ✨ Feature, 🔨 Refactor, 📬 API

#208 Refactoring of Order
  src/main/java/com/akatsuki/pioms/exchange/aggregate/RequestExchange.java
  src/main/java/com/akatsuki/pioms/exchange/service/ExchangeServiceImpl.java
  src/main/java/com/akatsuki/pioms/order/aggregate/OrderVO.java
  src/main/java/com/akatsuki/pioms/order/controller/AdminOrderController.java
  src/main/java/com/akatsuki/pioms/order/controller/FranchiseOrderController.java
  src/main/java/com/akatsuki/pioms/order/service/FranchiseOrderFacade.java
  src/main/java/com/akatsuki/pioms/order/service/OrderService.java
  src/main/java/com/akatsuki/pioms/order/service/OrderServiceImpl.java
  src/test/java/com/akatsuki/pioms/order/service/OrderFacadeTest.java
  src/test/java/com/akatsuki/pioms/ordertest.java
Labels: 🔨 Refactor

#211 Refactoring Order
  src/main/java/com/akatsuki/pioms/exchange/dto/ExchangeDTO.java
  src/main/java/com/akatsuki/pioms/exchange/dto/ExchangeProductDTO.java
  src/main/java/com/akatsuki/pioms/order/aggregate/OrderVO.java
  src/main/java/com/akatsuki/pioms/order/controller/AdminOrderController.java
  src/main/java/com/akatsuki/pioms/order/dto/OrderDTO.java
  src/main/java/com/akatsuki/pioms/order/service/AdminOrderFacade.java
Labels: 🔨 Refactor

#214 fix: fix test error
  src/main/java/com/akatsuki/pioms/invoice/service/InvoiceServiceImpl.java
  src/main/java/com/akatsuki/pioms/order/controller/AdminOrderController.java
  src/main/java/com/akatsuki/pioms/order/service/FranchiseOrderFacade.java
  src/main/java/com/akatsuki/pioms/order/service/OrderServiceImpl.java
  src/test/java/com/akatsuki/pioms/ask/service/AskServiceTests.java
  src/test/java/com/akatsuki/pioms/exchange/service/ExchangeServiceTest.java
  src/test/java/com/akatsuki/pioms/order/service/OrderFacadeTest.java
  src/test/java/com/akatsuki/pioms/ordertest.java
  src/test/java/com/akatsuki/pioms/specs/service/SpecsServiceTest.java
Labels: 🐞 BugFix, ✅ Test

#215 Administrator permission settings
  src/main/java/com/akatsuki/pioms/admin/aggregate/Admin.java
  src/main/java/com/akatsuki/pioms/admin/controller/AdminInfoController.java
  src/main/java/com/akatsuki/pioms/admin/dto/AdminDTO.java
  src/main/java/com/akatsuki/pioms/admin/service/AdminInfoService.java
  src/main/java/com/akatsuki/pioms/admin/service/AdminInfoServiceImpl.java
  src/main/java/com/akatsuki/pioms/config/SecurityConfig.java
  src/main/java/com/akatsuki/pioms/driver/aggregate/DeliveryDriver.java
  src/main/java/com/akatsuki/pioms/frowner/aggregate/FranchiseOwner.java
  src/main/java/com/akatsuki/pioms/login/controller/LoginController.java
  src/test/java/com/akatsuki/pioms/admin/service/AdminInfoServiceTest.java
Labels: ⚙ Setting, 🐞 BugFix, ✨ Feature, 🔨 Refactor, ✅ Test

#218 Refactoring TestCode of Ask
  src/main/java/com/akatsuki/pioms/ask/controller/AskAdminController.java
  src/main/java/com/akatsuki/pioms/ask/dto/AskDTO.java
  src/test/java/com/akatsuki/pioms/ask/service/AskServiceTests.java
Labels: 🔨 Refactor, ✅ Test

#223 #209 #212 Test for Notice (create - root admin) & Modify Invoice Status By Driver Function Implementation
  src/main/java/com/akatsuki/pioms/invoice/controller/DriverInvoiceController.java
  src/main/java/com/akatsuki/pioms/invoice/service/InvoiceService.java
  src/main/java/com/akatsuki/pioms/invoice/service/InvoiceServiceImpl.java
  src/main/java/com/akatsuki/pioms/notice/aggregate/NoticeVO.java
  src/main/java/com/akatsuki/pioms/notice/service/NoticeService.java
  src/test/java/com/akatsuki/pioms/notice/service/NoticeServiceTest.java
Labels: ✨ Feature, ✅ Test

#225 refactor: #224 Refactoring Notice, invoice(driver) Controller
  src/main/java/com/akatsuki/pioms/invoice/controller/DriverInvoiceController.java
  src/main/java/com/akatsuki/pioms/notice/controller/NoticeAdminController.java
  src/main/java/com/akatsuki/pioms/notice/controller/NoticeFranchiseController.java
  src/main/java/com/akatsuki/pioms/notice/service/NoticeService.java
Labels: 🔨 Refactor

#226 fix, refactor: fix error, refactoring controller url
  src/main/java/com/akatsuki/pioms/exchange/aggregate/ResponseExchange.java
  src/main/java/com/akatsuki/pioms/exchange/controller/AdminExchangeController.java
  src/main/java/com/akatsuki/pioms/invoice/aggregate/ResponseInvoice.java
  src/main/java/com/akatsuki/pioms/invoice/controller/AdminInvoiceController.java
  src/main/java/com/akatsuki/pioms/invoice/controller/FranchiseInvoiceController.java
  src/main/java/com/akatsuki/pioms/order/controller/FranchiseOrderController.java
  src/main/java/com/akatsuki/pioms/order/service/FranchiseOrderFacade.java
  src/main/java/com/akatsuki/pioms/order/service/OrderServiceImpl.java
  src/main/java/com/akatsuki/pioms/product/service/ProductService.java
  src/main/java/com/akatsuki/pioms/product/service/ProductServiceImpl.java
  src/main/java/com/akatsuki/pioms/specs/controller/AdminSpecsController.java
  src/main/java/com/akatsuki/pioms/specs/controller/FranchiseSpecsController.java
Labels: 🐞 BugFix, ✨ Feature, 🔨 Refactor

#228 Elastic Beanstalk deployment file
  .ebextensions/00-makeFiles.config
  .github/workflows/deploy.yml
  .platform/nginx.conf
  Procfile
  src/test/java/com/akatsuki/pioms/admin/service/AdminInfoServiceTest.java
  src/test/java/com/akatsuki/pioms/ask/service/AskServiceTests.java
  src/test/java/com/akatsuki/pioms/categoryFirst/service/CategoryFirstServiceTest.java
  src/test/java/com/akatsuki/pioms/categorySecond/service/CategorySecondServiceTest.java
  src/test/java/com/akatsuki/pioms/categoryThird/service/CategoryThirdServiceTest.java
  src/test/java/com/akatsuki/pioms/exchange/service/ExchangeServiceTest.java
  src/test/java/com/akatsuki/pioms/frwarehouse/service/FranchiseWarehouseServiceTest.java
  src/test/java/com/akatsuki/pioms/log/service/LogServiceImplTest.java
  src/test/java/com/akatsuki/pioms/notice/service/NoticeServiceTest.java
  src/test/java/com/akatsuki/pioms/order/service/OrderFacadeTest.java
  src/test/java/com/akatsuki/pioms/ordertest.java
  src/test/java/com/akatsuki/pioms/product/service/ProductServiceTest.java
  src/test/java/com/akatsuki/pioms/specs/service/SpecsServiceTest.java
Labels: 🌏 Deploy

#229 refactor: image upload with post product
  src/main/java/com/akatsuki/pioms/image/aggregate/Image.java
  src/main/java/com/akatsuki/pioms/image/service/ImageService.java
  src/main/java/com/akatsuki/pioms/order/aggregate/Order.java
  src/main/java/com/akatsuki/pioms/order/aggregate/OrderVO.java
  src/main/java/com/akatsuki/pioms/order/controller/AdminOrderController.java
  src/main/java/com/akatsuki/pioms/order/dto/OrderDTO.java
  src/main/java/com/akatsuki/pioms/order/service/AdminOrderFacade.java
  src/main/java/com/akatsuki/pioms/product/aggregate/RequestProduct.java
  src/main/java/com/akatsuki/pioms/product/controller/AdminProductController.java
  src/main/java/com/akatsuki/pioms/product/service/ProductServiceImpl.java
Labels: ✨ Feature, 🔨 Refactor

#230 refactoring ask of franchise code
  src/main/java/com/akatsuki/pioms/ask/controller/AskFranchiseController.java
  src/main/java/com/akatsuki/pioms/ask/service/AskService.java
  src/main/java/com/akatsuki/pioms/ask/service/AskServiceImpl.java
  src/main/java/com/akatsuki/pioms/exchange/service/ExchangeServiceImpl.java
  src/main/java/com/akatsuki/pioms/franchise/dto/FranchiseDTO.java
  src/main/java/com/akatsuki/pioms/frowner/controller/FrOwnerOnlyFrOwnerController.java
  src/main/java/com/akatsuki/pioms/frowner/dto/FranchiseOwnerDTO.java
  src/main/java/com/akatsuki/pioms/frowner/repository/FranchiseOwnerRepository.java
  src/main/java/com/akatsuki/pioms/frowner/service/FranchiseOwnerService.java
  src/main/java/com/akatsuki/pioms/frowner/service/FranchiseOwnerServiceImpl.java
  src/test/java/com/akatsuki/pioms/exchange/service/ExchangeServiceTest.java
Labels: 🔨 Refactor

#234 Test of Notice (create, modify, delete of Root admin), Test of ResponseDriverInvoice(read - Delivery_Status)delete of Root admin)
  src/main/java/com/akatsuki/pioms/invoice/service/InvoiceService.java
  src/main/java/com/akatsuki/pioms/invoice/service/InvoiceServiceImpl.java
  src/main/java/com/akatsuki/pioms/notice/dto/NoticeDTO.java
  src/test/java/com/akatsuki/pioms/invoice/service/InvoiceServiceTest.java
  src/test/java/com/akatsuki/pioms/notice/service/NoticeServiceTest.java
Labels: ✨ Feature, 🔨 Refactor, ✅ Test

#236 refactoring return VO
  src/main/java/com/akatsuki/pioms/config/SecurityConfig.java
  src/main/java/com/akatsuki/pioms/config/WebConfig.java
  src/main/java/com/akatsuki/pioms/exchange/aggregate/ExchangeProductVO.java
  src/main/java/com/akatsuki/pioms/exchange/aggregate/ResponseExchange.java
  src/main/java/com/akatsuki/pioms/exchange/controller/AdminExchangeController.java
  src/main/java/com/akatsuki/pioms/exchange/service/ExchangeService.java
  src/main/java/com/akatsuki/pioms/exchange/service/ExchangeServiceImpl.java
  src/main/java/com/akatsuki/pioms/invoice/service/InvoiceServiceImpl.java
  src/main/java/com/akatsuki/pioms/order/service/AdminOrderFacade.java
  src/main/java/com/akatsuki/pioms/product/aggregate/Product.java
Labels: 🐞 BugFix, 🔨 Refactor

#238 Test of ResponseDriverInvoice (read - Before Delivery_Status)
  src/test/java/com/akatsuki/pioms/invoice/service/InvoiceServiceTest.java
Labels: ✅ Test

#241 Test of ResponseDriverInvoice (read - Ing Delivery_Status)
  src/test/java/com/akatsuki/pioms/invoice/service/InvoiceServiceTest.java
Labels: ✅ Test

#242 Test of ResponseDriverInvoice (read - Complete Delivery_Status)
  src/test/java/com/akatsuki/pioms/invoice/service/InvoiceServiceTest.java
Labels: ✅ Test

#247 Exchange refactoring & favorite refactoring
  src/main/java/com/akatsuki/pioms/exchange/aggregate/EXCHANGE_STATUS.java
  src/main/java/com/akatsuki/pioms/exchange/aggregate/RequestExchange.java
  src/main/java/com/akatsuki/pioms/exchange/controller/AdminExchangeController.java
  src/main/java/com/akatsuki/pioms/exchange/controller/FranchiseExchangeController.java
  src/main/java/com/akatsuki/pioms/exchange/service/ExchangeService.java
  src/main/java/com/akatsuki/pioms/exchange/service/ExchangeServiceImpl.java
  src/main/java/com/akatsuki/pioms/frwarehouse/controller/franchiseWarehouseController.java
  src/main/java/com/akatsuki/pioms/frwarehouse/service/FranchiseWarehouseService.java
  src/main/java/com/akatsuki/pioms/frwarehouse/service/FranchiseWarehouseServiceImpl.java
  src/main/java/com/akatsuki/pioms/invoice/service/InvoiceServiceImpl.java
  src/main/java/com/akatsuki/pioms/product/aggregate/ResponseProduct.java
  src/main/java/com/akatsuki/pioms/product/dto/ProductDTO.java
Labels: 🔨 Refactor

#248 Test of ResponseDriverInvoice (read - Delivery_Status)
  src/test/java/com/akatsuki/pioms/invoice/service/InvoiceServiceTest.java
Labels: ✅ Test

#249 refactoring Log
  src/main/java/com/akatsuki/pioms/log/controller/LogController.java
  src/main/java/com/akatsuki/pioms/log/repository/LogRepository.java
  src/main/java/com/akatsuki/pioms/log/service/LogService.java
  src/main/java/com/akatsuki/pioms/log/service/LogServiceImpl.java
Labels: ✨ Feature, 🔨 Refactor

#250 refactor, fix, feat: refactoring Order, Exchange, Product, Franchise Warehouse ...
  src/main/java/com/akatsuki/pioms/exchange/controller/AdminExchangeController.java
  src/main/java/com/akatsuki/pioms/exchange/controller/FranchiseExchangeController.java
  src/main/java/com/akatsuki/pioms/exchange/repository/ExchangeRepository.java
  src/main/java/com/akatsuki/pioms/exchange/service/ExchangeService.java
  src/main/java/com/akatsuki/pioms/exchange/service/ExchangeServiceImpl.java
  src/main/java/com/akatsuki/pioms/franchise/aggregate/Franchise.java
  src/main/java/com/akatsuki/pioms/franchise/dto/FranchiseDTO.java
  src/main/java/com/akatsuki/pioms/franchise/service/FranchiseService.java
  src/main/java/com/akatsuki/pioms/franchise/service/FranchiseServiceImpl.java
  src/main/java/com/akatsuki/pioms/frwarehouse/dto/FranchiseWarehouseDTO.java
  src/main/java/com/akatsuki/pioms/frwarehouse/service/FranchiseWarehouseServiceImpl.java
  src/main/java/com/akatsuki/pioms/image/service/ImageService.java
  src/main/java/com/akatsuki/pioms/invoice/service/InvoiceServiceImpl.java
  src/main/java/com/akatsuki/pioms/order/aggregate/Order.java
  src/main/java/com/akatsuki/pioms/order/aggregate/OrderVO.java
  src/main/java/com/akatsuki/pioms/order/aggregate/RequestOrderVO.java
  src/main/java/com/akatsuki/pioms/order/aggregate/RequestPutOrderCheck.java
  src/main/java/com/akatsuki/pioms/order/controller/FranchiseOrderController.java
  src/main/java/com/akatsuki/pioms/order/dto/OrderDTO.java
  src/main/java/com/akatsuki/pioms/order/repository/OrderRepository.java
  src/main/java/com/akatsuki/pioms/order/service/AdminOrderFacade.java
  src/main/java/com/akatsuki/pioms/order/service/FranchiseOrderFacade.java
  src/main/java/com/akatsuki/pioms/order/service/OrderService.java
  src/main/java/com/akatsuki/pioms/order/service/OrderServiceImpl.java
  src/main/java/com/akatsuki/pioms/product/aggregate/ResponseProductWithImage.java
  src/main/java/com/akatsuki/pioms/product/controller/AdminProductController.java
  src/main/java/com/akatsuki/pioms/product/service/ProductService.java
  src/main/java/com/akatsuki/pioms/product/service/ProductServiceImpl.java
Labels: 🐞 BugFix, ✨ Feature, 🔨 Refactor

#253 Check and renew user JWT expiration(feat. redis)
  build.gradle
  src/main/java/com/akatsuki/pioms/admin/service/AdminInfoServiceImpl.java
  src/main/java/com/akatsuki/pioms/config/RedisConfig.java
  src/main/java/com/akatsuki/pioms/config/SecurityConfig.java
  src/main/java/com/akatsuki/pioms/config/WebConfig.java
  src/main/java/com/akatsuki/pioms/jwt/JWTFilter.java
  src/main/java/com/akatsuki/pioms/jwt/JWTUtil.java
  src/main/java/com/akatsuki/pioms/jwt/LoginFilter.java
  src/main/java/com/akatsuki/pioms/login/controller/LoginController.java
  src/main/java/com/akatsuki/pioms/login/controller/ReissueController.java
  src/main/java/com/akatsuki/pioms/login/service/LoginService.java
  src/main/java/com/akatsuki/pioms/login/service/LoginServiceImpl.java
  src/main/java/com/akatsuki/pioms/login/service/RedisTokenService.java
  src/main/java/com/akatsuki/pioms/user/aggregate/User.java
  src/main/java/com/akatsuki/pioms/user/dto/CustomUserDetails.java
  src/main/java/com/akatsuki/pioms/user/repository/UserRepository.java
  src/main/java/com/akatsuki/pioms/user/service/CustomUserDetailsService.java
Labels: 🐞 BugFix, ✨ Feature, 🔨 Refactor

#254 Fix CORS configuration in WebConfig and SecurityConfig
  src/main/java/com/akatsuki/pioms/config/SecurityConfig.java
  src/main/java/com/akatsuki/pioms/config/WebConfig.java
Labels: 🐞 BugFix, 🔨 Refactor

#255 Refactor, Fix, Feat: User, order, exchange
  src/main/java/com/akatsuki/pioms/admin/aggregate/Admin.java
  src/main/java/com/akatsuki/pioms/admin/repository/AdminRepository.java
  src/main/java/com/akatsuki/pioms/admin/service/AdminInfoService.java
  src/main/java/com/akatsuki/pioms/admin/service/AdminInfoServiceImpl.java
  src/main/java/com/akatsuki/pioms/config/ConvertUser.java
  src/main/java/com/akatsuki/pioms/driver/repository/DeliveryDriverRepository.java
  src/main/java/com/akatsuki/pioms/driver/service/DeliveryDriverService.java
  src/main/java/com/akatsuki/pioms/driver/service/DeliveryDriverServiceImpl.java
  src/main/java/com/akatsuki/pioms/exchange/controller/AdminExchangeController.java
  src/main/java/com/akatsuki/pioms/exchange/controller/FranchiseExchangeController.java
  src/main/java/com/akatsuki/pioms/exchange/service/ExchangeService.java
  src/main/java/com/akatsuki/pioms/exchange/service/ExchangeServiceImpl.java
  src/main/java/com/akatsuki/pioms/frowner/repository/FranchiseOwnerRepository.java
  src/main/java/com/akatsuki/pioms/frowner/service/FranchiseOwnerService.java
  src/main/java/com/akatsuki/pioms/frowner/service/FranchiseOwnerServiceImpl.java
  src/main/java/com/akatsuki/pioms/frwarehouse/service/FranchiseWarehouseService.java
  src/main/java/com/akatsuki/pioms/frwarehouse/service/FranchiseWarehouseServiceImpl.java
  src/main/java/com/akatsuki/pioms/invoice/service/InvoiceServiceImpl.java
  src/main/java/com/akatsuki/pioms/login/service/LoginServiceImpl.java
  src/main/java/com/akatsuki/pioms/order/aggregate/OrderProduct.java
  src/main/java/com/akatsuki/pioms/order/controller/AdminOrderController.java
  src/main/java/com/akatsuki/pioms/order/controller/FranchiseOrderController.java
  src/main/java/com/akatsuki/pioms/order/service/AdminOrderFacade.java
  src/main/java/com/akatsuki/pioms/order/service/FranchiseOrderFacade.java
  src/main/java/com/akatsuki/pioms/order/service/OrderService.java
  src/main/java/com/akatsuki/pioms/order/service/OrderServiceImpl.java
  src/main/java/com/akatsuki/pioms/product/service/ProductService.java
  src/main/java/com/akatsuki/pioms/product/service/ProductServiceImpl.java
  src/main/java/com/akatsuki/pioms/specs/service/SpecsService.java
  src/main/java/com/akatsuki/pioms/specs/service/SpecsServiceImpl.java
  src/main/java/com/akatsuki/pioms/user/aggregate/User.java
Labels: 🐞 BugFix, ✨ Feature, 🔨 Refactor

#256 refactoring ask BE
  src/main/java/com/akatsuki/pioms/ask/controller/AskAdminController.java
  src/main/java/com/akatsuki/pioms/ask/controller/AskFranchiseController.java
  src/main/java/com/akatsuki/pioms/ask/dto/AskListDTO.java
  src/main/java/com/akatsuki/pioms/ask/service/AskServiceImpl.java
Labels: 🔨 Refactor

#257 JWT token processing and security permission settings
  src/main/java/com/akatsuki/pioms/config/CorsConfig.java
  src/main/java/com/akatsuki/pioms/config/SecurityConfig.java
  src/main/java/com/akatsuki/pioms/jwt/CustomLogoutFilter.java
  src/main/java/com/akatsuki/pioms/jwt/JWTFilter.java
  src/main/java/com/akatsuki/pioms/jwt/JWTUtil.java
  src/main/java/com/akatsuki/pioms/jwt/LoginFilter.java
  src/main/java/com/akatsuki/pioms/login/controller/ReissueController.java
  src/main/java/com/akatsuki/pioms/login/service/LoginServiceImpl.java
  src/main/java/com/akatsuki/pioms/login/service/RedisTokenService.java
  src/main/java/com/akatsuki/pioms/user/dto/CustomUserDetails.java
Labels: 🐞 BugFix, ✨ Feature, 🔨 Refactor

#258 Increase access token time
  src/main/java/com/akatsuki/pioms/login/service/LoginServiceImpl.java
Labels: ⚙ Setting

#259 refactoring Ask BE
  src/main/java/com/akatsuki/pioms/ask/repository/AskRepository.java
  src/main/java/com/akatsuki/pioms/ask/service/AskServiceImpl.java
Labels: 🔨 Refactor

#260 Code refactoring & delete categoryFirst,Second feature
  build.gradle
  src/main/java/com/akatsuki/pioms/config/GlobalExceptionHandler.java
  src/main/java/com/akatsuki/pioms/config/WebConfig.java
  src/main/java/com/akatsuki/pioms/excel/ProductExcelAdminController.java
  src/main/java/com/akatsuki/pioms/product/aggregate/Product.java
  src/main/java/com/akatsuki/pioms/product/aggregate/ResponseProduct.java
  src/main/java/com/akatsuki/pioms/product/aggregate/ResponseProductWithImage.java
  src/main/java/com/akatsuki/pioms/product/controller/AdminProductController.java
  src/main/java/com/akatsuki/pioms/product/dto/ProductDTO.java
  src/main/java/com/akatsuki/pioms/product/etc/PRODUCT_GENDER.java
  src/main/java/com/akatsuki/pioms/product/service/ProductService.java
  src/main/java/com/akatsuki/pioms/product/service/ProductServiceImpl.java
Labels: ✨ Feature, 🔨 Refactor

#261 Code refactoring and delete categoryFirst,Second
  src/main/java/com/akatsuki/pioms/categoryFirst/controller/CategoryFirstController.java
  src/main/java/com/akatsuki/pioms/categoryFirst/service/CategoryFirstService.java
  src/main/java/com/akatsuki/pioms/categoryFirst/service/CategoryFirstServiceImpl.java
  src/main/java/com/akatsuki/pioms/categorySecond/controller/CategorySecondController.java
  src/main/java/com/akatsuki/pioms/categorySecond/service/CategorySecondService.java
  src/main/java/com/akatsuki/pioms/categorySecond/service/CategorySecondServiceImpl.java
  src/main/java/com/akatsuki/pioms/categoryThird/controller/CategoryThirdController.java
  src/main/java/com/akatsuki/pioms/categoryThird/service/CategoryThirdService.java
  src/main/java/com/akatsuki/pioms/categoryThird/service/CategoryThirdServiceImpl.java
Labels: ✨ Feature, 🔨 Refactor
